### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings.Implementation
  commentId: N:Sdl.Core.Settings.Implementation
  id: Sdl.Core.Settings.Implementation
  children:
  - Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  - Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
  - Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
  langs:
  - csharp
  - vb
  name: Sdl.Core.Settings.Implementation
  nameWithType: Sdl.Core.Settings.Implementation
  fullName: Sdl.Core.Settings.Implementation
  type: Namespace
  assemblies:
  - Sdl.Core.Settings
references:
- uid: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  commentId: T:Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  isExternal: true
  name: AbstractSettingsBundleAware
  nameWithType: AbstractSettingsBundleAware
  fullName: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
  commentId: T:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
  isExternal: true
  name: SettingsGroupTypeDescriptionProvider
  nameWithType: SettingsGroupTypeDescriptionProvider
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
  commentId: T:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
  isExternal: true
  name: SettingsGroupTypeDescriptor
  nameWithType: SettingsGroupTypeDescriptor
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
