### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings
  commentId: T:Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings
  id: ILanguageFontSettings
  parent: Sdl.TranslationStudio.Api.Editor
  children:
  - Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.LanguageFonts
  - Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.ResetDefaults
  - Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.SaveSettings
  langs:
  - csharp
  - vb
  name: ILanguageFontSettings
  nameWithType: ILanguageFontSettings
  fullName: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings
  type: Interface
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: public interface ILanguageFontSettings
    content.vb: Public Interface ILanguageFontSettings
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.SaveSettings
  commentId: M:Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.SaveSettings
  id: SaveSettings
  parent: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings
  langs:
  - csharp
  - vb
  name: SaveSettings()
  nameWithType: ILanguageFontSettings.SaveSettings()
  fullName: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.SaveSettings()
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: void SaveSettings()
    content.vb: Sub SaveSettings
  overload: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.SaveSettings*
- uid: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.ResetDefaults
  commentId: M:Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.ResetDefaults
  id: ResetDefaults
  parent: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings
  langs:
  - csharp
  - vb
  name: ResetDefaults()
  nameWithType: ILanguageFontSettings.ResetDefaults()
  fullName: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.ResetDefaults()
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: void ResetDefaults()
    content.vb: Sub ResetDefaults
  overload: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.ResetDefaults*
- uid: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.LanguageFonts
  commentId: P:Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.LanguageFonts
  id: LanguageFonts
  parent: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings
  langs:
  - csharp
  - vb
  name: LanguageFonts
  nameWithType: ILanguageFontSettings.LanguageFonts
  fullName: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.LanguageFonts
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: Dictionary<string, FontName> LanguageFonts { get; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,Sdl.FileTypeSupport.Framework.Formatting.FontName}
    content.vb: ReadOnly Property LanguageFonts As Dictionary(Of String, FontName)
  overload: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.LanguageFonts*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Sdl.TranslationStudio.Api.Editor
  commentId: N:Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: Sdl.TranslationStudio.Api.Editor
  nameWithType: Sdl.TranslationStudio.Api.Editor
  fullName: Sdl.TranslationStudio.Api.Editor
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.SaveSettings*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.SaveSettings
  isExternal: true
  name: SaveSettings
  nameWithType: ILanguageFontSettings.SaveSettings
  fullName: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.SaveSettings
- uid: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.ResetDefaults*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.ResetDefaults
  isExternal: true
  name: ResetDefaults
  nameWithType: ILanguageFontSettings.ResetDefaults
  fullName: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.ResetDefaults
- uid: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.LanguageFonts*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.LanguageFonts
  isExternal: true
  name: LanguageFonts
  nameWithType: ILanguageFontSettings.LanguageFonts
  fullName: Sdl.TranslationStudio.Api.Editor.ILanguageFontSettings.LanguageFonts
- uid: System.Collections.Generic.Dictionary{System.String,Sdl.FileTypeSupport.Framework.Formatting.FontName}
  commentId: T:System.Collections.Generic.Dictionary{System.String,Sdl.FileTypeSupport.Framework.Formatting.FontName}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  name: Dictionary<String, FontName>
  nameWithType: Dictionary<String, FontName>
  fullName: System.Collections.Generic.Dictionary<System.String, Sdl.FileTypeSupport.Framework.Formatting.FontName>
  nameWithType.vb: Dictionary(Of String, FontName)
  fullName.vb: System.Collections.Generic.Dictionary(Of System.String, Sdl.FileTypeSupport.Framework.Formatting.FontName)
  name.vb: Dictionary(Of String, FontName)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Sdl.FileTypeSupport.Framework.Formatting.FontName
    name: FontName
    nameWithType: FontName
    fullName: Sdl.FileTypeSupport.Framework.Formatting.FontName
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Sdl.FileTypeSupport.Framework.Formatting.FontName
    name: FontName
    nameWithType: FontName
    fullName: Sdl.FileTypeSupport.Framework.Formatting.FontName
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
