### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration
  commentId: T:Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration
  id: ITranslatableDocumentEditorConfiguration
  parent: Sdl.TranslationStudio.Api.Editor
  children:
  - Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.Editor
  - Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.OpenDocumentMode
  langs:
  - csharp
  - vb
  name: ITranslatableDocumentEditorConfiguration
  nameWithType: ITranslatableDocumentEditorConfiguration
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration
  type: Interface
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: 'public interface ITranslatableDocumentEditorConfiguration : IEditorConfiguration'
    content.vb: >-
      Public Interface ITranslatableDocumentEditorConfiguration
          Inherits IEditorConfiguration
  inheritedMembers:
  - Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Id
  - Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Name
  - Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Description
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.Editor
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.Editor
  id: Editor
  parent: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration
  langs:
  - csharp
  - vb
  name: Editor
  nameWithType: ITranslatableDocumentEditorConfiguration.Editor
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.Editor
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: ITranslatableDocumentEditor Editor { get; }
    parameters: []
    return:
      type: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditor
    content.vb: ReadOnly Property Editor As ITranslatableDocumentEditor
  overload: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.Editor*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.OpenDocumentMode
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.OpenDocumentMode
  id: OpenDocumentMode
  parent: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration
  langs:
  - csharp
  - vb
  name: OpenDocumentMode
  nameWithType: ITranslatableDocumentEditorConfiguration.OpenDocumentMode
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.OpenDocumentMode
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: OpenDocumentMode OpenDocumentMode { get; }
    parameters: []
    return:
      type: Sdl.TranslationStudio.Api.Editor.OpenDocumentMode
    content.vb: ReadOnly Property OpenDocumentMode As OpenDocumentMode
  overload: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.OpenDocumentMode*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Sdl.TranslationStudio.Api.Editor
  commentId: N:Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: Sdl.TranslationStudio.Api.Editor
  nameWithType: Sdl.TranslationStudio.Api.Editor
  fullName: Sdl.TranslationStudio.Api.Editor
- uid: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Id
  commentId: P:Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Id
  parent: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration
  isExternal: true
  name: Id
  nameWithType: IEditorConfiguration.Id
  fullName: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Id
- uid: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Name
  commentId: P:Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Name
  parent: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration
  isExternal: true
  name: Name
  nameWithType: IEditorConfiguration.Name
  fullName: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Name
- uid: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Description
  commentId: P:Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Description
  parent: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration
  isExternal: true
  name: Description
  nameWithType: IEditorConfiguration.Description
  fullName: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration.Description
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration
  commentId: T:Sdl.TranslationStudio.Api.Editor.IEditorConfiguration
  parent: Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: IEditorConfiguration
  nameWithType: IEditorConfiguration
  fullName: Sdl.TranslationStudio.Api.Editor.IEditorConfiguration
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.Editor*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.Editor
  isExternal: true
  name: Editor
  nameWithType: ITranslatableDocumentEditorConfiguration.Editor
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.Editor
- uid: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditor
  commentId: T:Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditor
  parent: Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: ITranslatableDocumentEditor
  nameWithType: ITranslatableDocumentEditor
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditor
- uid: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.OpenDocumentMode*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.OpenDocumentMode
  isExternal: true
  name: OpenDocumentMode
  nameWithType: ITranslatableDocumentEditorConfiguration.OpenDocumentMode
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslatableDocumentEditorConfiguration.OpenDocumentMode
- uid: Sdl.TranslationStudio.Api.Editor.OpenDocumentMode
  commentId: T:Sdl.TranslationStudio.Api.Editor.OpenDocumentMode
  parent: Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: OpenDocumentMode
  nameWithType: OpenDocumentMode
  fullName: Sdl.TranslationStudio.Api.Editor.OpenDocumentMode
