### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.Start.IStartViewSettings
  commentId: T:Sdl.TranslationStudio.Api.Start.IStartViewSettings
  id: IStartViewSettings
  parent: Sdl.TranslationStudio.Api.Start
  children:
  - Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowProjectsDueWithinDays
  - Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowTasksDueWithinDays
  langs:
  - csharp
  - vb
  name: IStartViewSettings
  nameWithType: IStartViewSettings
  fullName: Sdl.TranslationStudio.Api.Start.IStartViewSettings
  type: Interface
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Start
  syntax:
    content: 'public interface IStartViewSettings : ISettingsGroup, INotifyPropertyChanged, IEditableObject'
    content.vb: >-
      Public Interface IStartViewSettings
          Inherits ISettingsGroup, INotifyPropertyChanged, IEditableObject
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowTasksDueWithinDays
  commentId: P:Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowTasksDueWithinDays
  id: ShowTasksDueWithinDays
  parent: Sdl.TranslationStudio.Api.Start.IStartViewSettings
  langs:
  - csharp
  - vb
  name: ShowTasksDueWithinDays
  nameWithType: IStartViewSettings.ShowTasksDueWithinDays
  fullName: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowTasksDueWithinDays
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Start
  syntax:
    content: Setting<int> ShowTasksDueWithinDays { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Int32}
    content.vb: ReadOnly Property ShowTasksDueWithinDays As Setting(Of Integer)
  overload: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowTasksDueWithinDays*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowProjectsDueWithinDays
  commentId: P:Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowProjectsDueWithinDays
  id: ShowProjectsDueWithinDays
  parent: Sdl.TranslationStudio.Api.Start.IStartViewSettings
  langs:
  - csharp
  - vb
  name: ShowProjectsDueWithinDays
  nameWithType: IStartViewSettings.ShowProjectsDueWithinDays
  fullName: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowProjectsDueWithinDays
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Start
  syntax:
    content: Setting<int> ShowProjectsDueWithinDays { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Int32}
    content.vb: ReadOnly Property ShowProjectsDueWithinDays As Setting(Of Integer)
  overload: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowProjectsDueWithinDays*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Sdl.TranslationStudio.Api.Start
  commentId: N:Sdl.TranslationStudio.Api.Start
  isExternal: true
  name: Sdl.TranslationStudio.Api.Start
  nameWithType: Sdl.TranslationStudio.Api.Start
  fullName: Sdl.TranslationStudio.Api.Start
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowTasksDueWithinDays*
  commentId: Overload:Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowTasksDueWithinDays
  isExternal: true
  name: ShowTasksDueWithinDays
  nameWithType: IStartViewSettings.ShowTasksDueWithinDays
  fullName: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowTasksDueWithinDays
- uid: Sdl.Core.Settings.Setting{System.Int32}
  commentId: '!:Sdl.Core.Settings.Setting{System.Int32}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<Int32>
  nameWithType: Setting<Int32>
  fullName: Sdl.Core.Settings.Setting<System.Int32>
  nameWithType.vb: Setting(Of Int32)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.Int32)
  name.vb: Setting(Of Int32)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.Setting`1
  isExternal: true
  name: Setting<>
  nameWithType: Setting<>
  fullName: Sdl.Core.Settings.Setting<>
  nameWithType.vb: Setting(Of )
  fullName.vb: Sdl.Core.Settings.Setting(Of )
  name.vb: Setting(Of )
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowProjectsDueWithinDays*
  commentId: Overload:Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowProjectsDueWithinDays
  isExternal: true
  name: ShowProjectsDueWithinDays
  nameWithType: IStartViewSettings.ShowProjectsDueWithinDays
  fullName: Sdl.TranslationStudio.Api.Start.IStartViewSettings.ShowProjectsDueWithinDays
