### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute
  commentId: T:Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute
  id: RequiresSettingsAttribute
  parent: Sdl.ProjectAutomation.AutomaticTasks
  children:
  - Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.#ctor(System.Type,System.Type)
  - Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsPageType
  - Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsType
  langs:
  - csharp
  - vb
  name: RequiresSettingsAttribute
  nameWithType: RequiresSettingsAttribute
  fullName: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute
  type: Class
  source:
    path: Sdl.ProjectAutomation.AutomaticTasks
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.AutomaticTasks
  namespace: Sdl.ProjectAutomation.AutomaticTasks
  summary: "\nAttribute class to define the settings info\n"
  syntax:
    content: >-
      [AttributeUsage(AttributeTargets.Class)]

      public class RequiresSettingsAttribute : AuxiliaryExtensionAttribute
    content.vb: >-
      <AttributeUsage(AttributeTargets.Class)>

      Public Class RequiresSettingsAttribute
          Inherits AuxiliaryExtensionAttribute
  inheritance:
  - System.Object
  attributes:
  - type: System.AttributeUsageAttribute
    ctor: System.AttributeUsageAttribute.#ctor(System.AttributeTargets)
    arguments:
    - type: System.AttributeTargets
      value: 4
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.#ctor(System.Type,System.Type)
  commentId: M:Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.#ctor(System.Type,System.Type)
  id: '#ctor(System.Type,System.Type)'
  parent: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute
  langs:
  - csharp
  - vb
  name: RequiresSettingsAttribute(Type, Type)
  nameWithType: RequiresSettingsAttribute.RequiresSettingsAttribute(Type, Type)
  fullName: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.RequiresSettingsAttribute(System.Type, System.Type)
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.AutomaticTasks
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.AutomaticTasks
  namespace: Sdl.ProjectAutomation.AutomaticTasks
  summary: "\nconstructor of the RequiresSettings\n"
  syntax:
    content: public RequiresSettingsAttribute(Type settingsType, Type settingsPageType)
    parameters:
    - id: settingsType
      type: System.Type
    - id: settingsPageType
      type: System.Type
    content.vb: Public Sub New(settingsType As Type, settingsPageType As Type)
  overload: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsType
  commentId: P:Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsType
  id: SettingsType
  parent: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute
  langs:
  - csharp
  - vb
  name: SettingsType
  nameWithType: RequiresSettingsAttribute.SettingsType
  fullName: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsType
  type: Property
  source:
    path: Sdl.ProjectAutomation.AutomaticTasks
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.AutomaticTasks
  namespace: Sdl.ProjectAutomation.AutomaticTasks
  summary: "\nGets the type of the task settings class\n"
  syntax:
    content: public Type SettingsType { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: Public ReadOnly Property SettingsType As Type
  overload: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsType*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsPageType
  commentId: P:Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsPageType
  id: SettingsPageType
  parent: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute
  langs:
  - csharp
  - vb
  name: SettingsPageType
  nameWithType: RequiresSettingsAttribute.SettingsPageType
  fullName: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsPageType
  type: Property
  source:
    path: Sdl.ProjectAutomation.AutomaticTasks
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.AutomaticTasks
  namespace: Sdl.ProjectAutomation.AutomaticTasks
  summary: "\nGets the type of the task settings page class\n"
  syntax:
    content: public Type SettingsPageType { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: Public ReadOnly Property SettingsPageType As Type
  overload: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsPageType*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.ProjectAutomation.AutomaticTasks
  commentId: N:Sdl.ProjectAutomation.AutomaticTasks
  isExternal: true
  name: Sdl.ProjectAutomation.AutomaticTasks
  nameWithType: Sdl.ProjectAutomation.AutomaticTasks
  fullName: Sdl.ProjectAutomation.AutomaticTasks
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.#ctor
  isExternal: true
  name: RequiresSettingsAttribute
  nameWithType: RequiresSettingsAttribute.RequiresSettingsAttribute
  fullName: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.RequiresSettingsAttribute
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsType*
  commentId: Overload:Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsType
  isExternal: true
  name: SettingsType
  nameWithType: RequiresSettingsAttribute.SettingsType
  fullName: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsType
- uid: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsPageType*
  commentId: Overload:Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsPageType
  isExternal: true
  name: SettingsPageType
  nameWithType: RequiresSettingsAttribute.SettingsPageType
  fullName: Sdl.ProjectAutomation.AutomaticTasks.RequiresSettingsAttribute.SettingsPageType
