### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Core.ValueStatus
  commentId: T:Sdl.ProjectAutomation.Core.ValueStatus
  id: ValueStatus
  parent: Sdl.ProjectAutomation.Core
  children:
  - Sdl.ProjectAutomation.Core.ValueStatus.Complete
  - Sdl.ProjectAutomation.Core.ValueStatus.None
  - Sdl.ProjectAutomation.Core.ValueStatus.OutOfDate
  - Sdl.ProjectAutomation.Core.ValueStatus.Partial
  langs:
  - csharp
  - vb
  name: ValueStatus
  nameWithType: ValueStatus
  fullName: Sdl.ProjectAutomation.Core.ValueStatus
  type: Enum
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  summary: "\nEnum with possible status values for various types of statistics.\n"
  syntax:
    content: public enum ValueStatus
    content.vb: Public Enum ValueStatus
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.ProjectAutomation.Core.ValueStatus.None
  commentId: F:Sdl.ProjectAutomation.Core.ValueStatus.None
  id: None
  parent: Sdl.ProjectAutomation.Core.ValueStatus
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ValueStatus.None
  fullName: Sdl.ProjectAutomation.Core.ValueStatus.None
  type: Field
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  summary: "\nNo statistics have been computed yet.\n"
  syntax:
    content: None = 0
    return:
      type: Sdl.ProjectAutomation.Core.ValueStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Core.ValueStatus.Partial
  commentId: F:Sdl.ProjectAutomation.Core.ValueStatus.Partial
  id: Partial
  parent: Sdl.ProjectAutomation.Core.ValueStatus
  langs:
  - csharp
  - vb
  name: Partial
  nameWithType: ValueStatus.Partial
  fullName: Sdl.ProjectAutomation.Core.ValueStatus.Partial
  type: Field
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  summary: "\nPartial statistics have been computed. This is only valid for aggregate statistics values and means that for some of the items\nstatistics have been computed, but not for all of them.\n"
  syntax:
    content: Partial = 1
    return:
      type: Sdl.ProjectAutomation.Core.ValueStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Core.ValueStatus.OutOfDate
  commentId: F:Sdl.ProjectAutomation.Core.ValueStatus.OutOfDate
  id: OutOfDate
  parent: Sdl.ProjectAutomation.Core.ValueStatus
  langs:
  - csharp
  - vb
  name: OutOfDate
  nameWithType: ValueStatus.OutOfDate
  fullName: Sdl.ProjectAutomation.Core.ValueStatus.OutOfDate
  type: Field
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  summary: "\nStatistics are available for all items, but some of the statistics are out of date. This can be the case if a file&apos;s contents\nhave changed after statistics were last computed.\n"
  syntax:
    content: OutOfDate = 2
    return:
      type: Sdl.ProjectAutomation.Core.ValueStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Core.ValueStatus.Complete
  commentId: F:Sdl.ProjectAutomation.Core.ValueStatus.Complete
  id: Complete
  parent: Sdl.ProjectAutomation.Core.ValueStatus
  langs:
  - csharp
  - vb
  name: Complete
  nameWithType: ValueStatus.Complete
  fullName: Sdl.ProjectAutomation.Core.ValueStatus.Complete
  type: Field
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  summary: "\nFully up-to-date statistics are available.\n"
  syntax:
    content: Complete = 3
    return:
      type: Sdl.ProjectAutomation.Core.ValueStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.ProjectAutomation.Core
  commentId: N:Sdl.ProjectAutomation.Core
  isExternal: true
  name: Sdl.ProjectAutomation.Core
  nameWithType: Sdl.ProjectAutomation.Core
  fullName: Sdl.ProjectAutomation.Core
- uid: Sdl.ProjectAutomation.Core.ValueStatus
  commentId: T:Sdl.ProjectAutomation.Core.ValueStatus
  parent: Sdl.ProjectAutomation.Core
  isExternal: true
  name: ValueStatus
  nameWithType: ValueStatus
  fullName: Sdl.ProjectAutomation.Core.ValueStatus
