### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer
  commentId: T:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer
  id: IPhraseExtractionConfigurer
  parent: Sdl.TranslationStudio.Api.Editor
  children:
  - Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.AddExtraction(System.String)
  - Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.Configure(System.String)
  - Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.DeleteExtraction(System.String)
  - Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.GetCurrentConfiguaration
  - Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.UpdateExtraction(System.String)
  langs:
  - csharp
  - vb
  name: IPhraseExtractionConfigurer
  nameWithType: IPhraseExtractionConfigurer
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer
  type: Interface
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nThe remoting interface to configuration the phrase extraction\n"
  syntax:
    content: public interface IPhraseExtractionConfigurer
    content.vb: Public Interface IPhraseExtractionConfigurer
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.Configure(System.String)
  commentId: M:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.Configure(System.String)
  id: Configure(System.String)
  parent: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer
  langs:
  - csharp
  - vb
  name: Configure(String)
  nameWithType: IPhraseExtractionConfigurer.Configure(String)
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.Configure(System.String)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nConfigure the phrase extraction service\n"
  syntax:
    content: void Configure(string info)
    parameters:
    - id: info
      type: System.String
    content.vb: Sub Configure(info As String)
  overload: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.Configure*
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.AddExtraction(System.String)
  commentId: M:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.AddExtraction(System.String)
  id: AddExtraction(System.String)
  parent: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer
  langs:
  - csharp
  - vb
  name: AddExtraction(String)
  nameWithType: IPhraseExtractionConfigurer.AddExtraction(String)
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.AddExtraction(System.String)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nAdd an extraction\n"
  syntax:
    content: void AddExtraction(string info)
    parameters:
    - id: info
      type: System.String
    content.vb: Sub AddExtraction(info As String)
  overload: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.AddExtraction*
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.DeleteExtraction(System.String)
  commentId: M:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.DeleteExtraction(System.String)
  id: DeleteExtraction(System.String)
  parent: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer
  langs:
  - csharp
  - vb
  name: DeleteExtraction(String)
  nameWithType: IPhraseExtractionConfigurer.DeleteExtraction(String)
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.DeleteExtraction(System.String)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\ndelete an extraction\n"
  syntax:
    content: void DeleteExtraction(string tmInfo)
    parameters:
    - id: tmInfo
      type: System.String
    content.vb: Sub DeleteExtraction(tmInfo As String)
  overload: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.DeleteExtraction*
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.UpdateExtraction(System.String)
  commentId: M:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.UpdateExtraction(System.String)
  id: UpdateExtraction(System.String)
  parent: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer
  langs:
  - csharp
  - vb
  name: UpdateExtraction(String)
  nameWithType: IPhraseExtractionConfigurer.UpdateExtraction(String)
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.UpdateExtraction(System.String)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nupdate the extraction\n"
  syntax:
    content: void UpdateExtraction(string info)
    parameters:
    - id: info
      type: System.String
    content.vb: Sub UpdateExtraction(info As String)
  overload: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.UpdateExtraction*
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.GetCurrentConfiguaration
  commentId: M:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.GetCurrentConfiguaration
  id: GetCurrentConfiguaration
  parent: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer
  langs:
  - csharp
  - vb
  name: GetCurrentConfiguaration()
  nameWithType: IPhraseExtractionConfigurer.GetCurrentConfiguaration()
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.GetCurrentConfiguaration()
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nretrieve the current extraction configuration\n"
  syntax:
    content: string GetCurrentConfiguaration()
    return:
      type: System.String
    content.vb: Function GetCurrentConfiguaration As String
  overload: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.GetCurrentConfiguaration*
references:
- uid: Sdl.TranslationStudio.Api.Editor
  commentId: N:Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: Sdl.TranslationStudio.Api.Editor
  nameWithType: Sdl.TranslationStudio.Api.Editor
  fullName: Sdl.TranslationStudio.Api.Editor
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.Configure*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.Configure
  isExternal: true
  name: Configure
  nameWithType: IPhraseExtractionConfigurer.Configure
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.Configure
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.AddExtraction*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.AddExtraction
  isExternal: true
  name: AddExtraction
  nameWithType: IPhraseExtractionConfigurer.AddExtraction
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.AddExtraction
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.DeleteExtraction*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.DeleteExtraction
  isExternal: true
  name: DeleteExtraction
  nameWithType: IPhraseExtractionConfigurer.DeleteExtraction
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.DeleteExtraction
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.UpdateExtraction*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.UpdateExtraction
  isExternal: true
  name: UpdateExtraction
  nameWithType: IPhraseExtractionConfigurer.UpdateExtraction
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.UpdateExtraction
- uid: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.GetCurrentConfiguaration*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.GetCurrentConfiguaration
  isExternal: true
  name: GetCurrentConfiguaration
  nameWithType: IPhraseExtractionConfigurer.GetCurrentConfiguaration
  fullName: Sdl.TranslationStudio.Api.Editor.IPhraseExtractionConfigurer.GetCurrentConfiguaration
