### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  id: ImportSettings.ImportTUProcessingMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessBothTUs
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessCleanedTUOnly
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessRawTUOnly
  langs:
  - csharp
  - vb
  name: ImportSettings.ImportTUProcessingMode
  nameWithType: ImportSettings.ImportTUProcessingMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  type: Enum
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nControls whether cleanup heuristics are applied to TUs being read and which ones are \nprocessed by the importer.\n"
  syntax:
    content: public enum ImportTUProcessingMode
    content.vb: Public Enum ImportTUProcessingMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessCleanedTUOnly
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessCleanedTUOnly
  id: ProcessCleanedTUOnly
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  langs:
  - csharp
  - vb
  name: ProcessCleanedTUOnly
  nameWithType: ImportSettings.ImportTUProcessingMode.ProcessCleanedTUOnly
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessCleanedTUOnly
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nApply flavor-specific cleanup heuristics to a TU read from the input stream \nand process only the cleaned TU. This is the default.\n"
  syntax:
    content: ProcessCleanedTUOnly = 0
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessRawTUOnly
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessRawTUOnly
  id: ProcessRawTUOnly
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  langs:
  - csharp
  - vb
  name: ProcessRawTUOnly
  nameWithType: ImportSettings.ImportTUProcessingMode.ProcessRawTUOnly
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessRawTUOnly
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nApply only minimal cleanup (such as trimming) to a TU read from the input stream \nand process the raw TU, without additional, flavor-specific cleanup.\n"
  syntax:
    content: ProcessRawTUOnly = 1
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessBothTUs
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessBothTUs
  id: ProcessBothTUs
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  langs:
  - csharp
  - vb
  name: ProcessBothTUs
  nameWithType: ImportSettings.ImportTUProcessingMode.ProcessBothTUs
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode.ProcessBothTUs
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nProcess both the raw TU as well as the cleaned one. \n"
  syntax:
    content: ProcessBothTUs = 2
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: ImportSettings.ImportTUProcessingMode
  nameWithType: ImportSettings.ImportTUProcessingMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.ImportTUProcessingMode
