### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  commentId: T:Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  id: SourceTrackChangesLookupMode
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.LookupWithTrackChangesAccepted
  - Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.LookupWithTrackChangesRejected
  - Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.NoLookup
  langs:
  - csharp
  - vb
  name: SourceTrackChangesLookupMode
  nameWithType: SourceTrackChangesLookupMode
  fullName: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  type: Enum
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nthe way to handle segments with source track changes in TM search\n"
  syntax:
    content: public enum SourceTrackChangesLookupMode
    content.vb: Public Enum SourceTrackChangesLookupMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.NoLookup
  commentId: F:Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.NoLookup
  id: NoLookup
  parent: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  langs:
  - csharp
  - vb
  name: NoLookup
  nameWithType: SourceTrackChangesLookupMode.NoLookup
  fullName: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.NoLookup
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nDo not perform lookup\n"
  syntax:
    content: NoLookup = 1
    return:
      type: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.LookupWithTrackChangesRejected
  commentId: F:Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.LookupWithTrackChangesRejected
  id: LookupWithTrackChangesRejected
  parent: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  langs:
  - csharp
  - vb
  name: LookupWithTrackChangesRejected
  nameWithType: SourceTrackChangesLookupMode.LookupWithTrackChangesRejected
  fullName: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.LookupWithTrackChangesRejected
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nperfrom lookup with track changes rejected\n"
  syntax:
    content: LookupWithTrackChangesRejected = 0
    return:
      type: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.LookupWithTrackChangesAccepted
  commentId: F:Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.LookupWithTrackChangesAccepted
  id: LookupWithTrackChangesAccepted
  parent: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  langs:
  - csharp
  - vb
  name: LookupWithTrackChangesAccepted
  nameWithType: SourceTrackChangesLookupMode.LookupWithTrackChangesAccepted
  fullName: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode.LookupWithTrackChangesAccepted
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nperform lookup with track changes accepted\n"
  syntax:
    content: LookupWithTrackChangesAccepted = 2
    return:
      type: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  commentId: T:Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: SourceTrackChangesLookupMode
  nameWithType: SourceTrackChangesLookupMode
  fullName: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
