### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  commentId: T:Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  id: TranslationUpdateMode
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.TranslationUpdateMode.KeepExistingTranslation
  - Sdl.ProjectAutomation.Settings.TranslationUpdateMode.OverwriteExistingTranslation
  - Sdl.ProjectAutomation.Settings.TranslationUpdateMode.OverwriteExistingTranslationIfBetterMatch
  langs:
  - csharp
  - vb
  name: TranslationUpdateMode
  nameWithType: TranslationUpdateMode
  fullName: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  type: Enum
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nTranslation update modes used in the Translate automatic task.\n"
  syntax:
    content: public enum TranslationUpdateMode
    content.vb: Public Enum TranslationUpdateMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.ProjectAutomation.Settings.TranslationUpdateMode.KeepExistingTranslation
  commentId: F:Sdl.ProjectAutomation.Settings.TranslationUpdateMode.KeepExistingTranslation
  id: KeepExistingTranslation
  parent: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  langs:
  - csharp
  - vb
  name: KeepExistingTranslation
  nameWithType: TranslationUpdateMode.KeepExistingTranslation
  fullName: Sdl.ProjectAutomation.Settings.TranslationUpdateMode.KeepExistingTranslation
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nKeep existing bilingual segments (don&apos;t overwrite existing translations)\n"
  syntax:
    content: KeepExistingTranslation = 0
    return:
      type: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.TranslationUpdateMode.OverwriteExistingTranslationIfBetterMatch
  commentId: F:Sdl.ProjectAutomation.Settings.TranslationUpdateMode.OverwriteExistingTranslationIfBetterMatch
  id: OverwriteExistingTranslationIfBetterMatch
  parent: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  langs:
  - csharp
  - vb
  name: OverwriteExistingTranslationIfBetterMatch
  nameWithType: TranslationUpdateMode.OverwriteExistingTranslationIfBetterMatch
  fullName: Sdl.ProjectAutomation.Settings.TranslationUpdateMode.OverwriteExistingTranslationIfBetterMatch
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nOverwrite existing translations if the current TM yields a better match than the one recorded in the input\n"
  syntax:
    content: OverwriteExistingTranslationIfBetterMatch = 1
    return:
      type: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.TranslationUpdateMode.OverwriteExistingTranslation
  commentId: F:Sdl.ProjectAutomation.Settings.TranslationUpdateMode.OverwriteExistingTranslation
  id: OverwriteExistingTranslation
  parent: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  langs:
  - csharp
  - vb
  name: OverwriteExistingTranslation
  nameWithType: TranslationUpdateMode.OverwriteExistingTranslation
  fullName: Sdl.ProjectAutomation.Settings.TranslationUpdateMode.OverwriteExistingTranslation
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nAlways overwrite existing translations, except locked or PerfectMatch translation\n"
  syntax:
    content: OverwriteExistingTranslation = 2
    return:
      type: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  commentId: T:Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: TranslationUpdateMode
  nameWithType: TranslationUpdateMode
  fullName: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
