### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.ReturningPackageSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ReturningPackageSettings
  id: ReturningPackageSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.ReturningPackageSettings.#ctor
  - Sdl.ProjectAutomation.Settings.ReturningPackageSettings.RunVerificationBeforeReturningPackage
  langs:
  - csharp
  - vb
  name: ReturningPackageSettings
  nameWithType: ReturningPackageSettings
  fullName: Sdl.ProjectAutomation.Settings.ReturningPackageSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSettings that relate to the return package when the create project package is created.\n"
  syntax:
    content: 'public class ReturningPackageSettings : SettingsGroup'
    content.vb: >-
      Public Class ReturningPackageSettings
          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.ReturningPackageSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.ReturningPackageSettings
  langs:
  - csharp
  - vb
  name: ReturningPackageSettings()
  nameWithType: ReturningPackageSettings.ReturningPackageSettings()
  fullName: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.ReturningPackageSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  syntax:
    content: public ReturningPackageSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.RunVerificationBeforeReturningPackage
  commentId: P:Sdl.ProjectAutomation.Settings.ReturningPackageSettings.RunVerificationBeforeReturningPackage
  id: RunVerificationBeforeReturningPackage
  parent: Sdl.ProjectAutomation.Settings.ReturningPackageSettings
  langs:
  - csharp
  - vb
  name: RunVerificationBeforeReturningPackage
  nameWithType: ReturningPackageSettings.RunVerificationBeforeReturningPackage
  fullName: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.RunVerificationBeforeReturningPackage
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSetting that specifies whether the return package should run a verification before creation.\n"
  syntax:
    content: public bool RunVerificationBeforeReturningPackage { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property RunVerificationBeforeReturningPackage As Boolean
  overload: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.RunVerificationBeforeReturningPackage*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ReturningPackageSettings.#ctor
  isExternal: true
  name: ReturningPackageSettings
  nameWithType: ReturningPackageSettings.ReturningPackageSettings
  fullName: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.ReturningPackageSettings
- uid: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.RunVerificationBeforeReturningPackage*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ReturningPackageSettings.RunVerificationBeforeReturningPackage
  isExternal: true
  name: RunVerificationBeforeReturningPackage
  nameWithType: ReturningPackageSettings.RunVerificationBeforeReturningPackage
  fullName: Sdl.ProjectAutomation.Settings.ReturningPackageSettings.RunVerificationBeforeReturningPackage
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
