### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.TranslationCountSettings
  commentId: T:Sdl.ProjectAutomation.Settings.TranslationCountSettings
  id: TranslationCountSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.TranslationCountSettings.#ctor
  - Sdl.ProjectAutomation.Settings.TranslationCountSettings.CreateReport
  - Sdl.ProjectAutomation.Settings.TranslationCountSettings.GetDefaultValue(System.String)
  langs:
  - csharp
  - vb
  name: TranslationCountSettings
  nameWithType: TranslationCountSettings
  fullName: Sdl.ProjectAutomation.Settings.TranslationCountSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSettings group class for the Translation count automatic task settings.\n"
  syntax:
    content: 'public class TranslationCountSettings : SettingsGroup'
    content.vb: >-
      Public Class TranslationCountSettings
          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.TranslationCountSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.TranslationCountSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.TranslationCountSettings
  langs:
  - csharp
  - vb
  name: TranslationCountSettings()
  nameWithType: TranslationCountSettings.TranslationCountSettings()
  fullName: Sdl.ProjectAutomation.Settings.TranslationCountSettings.TranslationCountSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nDefault constructor. You should never create this object manually. Use <xref href=\"Sdl.Core.Settings.ISettingsBundle.GetSettingsGroup(System.String)\" data-throw-if-not-resolved=\"false\"></xref> instead.\n"
  syntax:
    content: public TranslationCountSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.TranslationCountSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.TranslationCountSettings.GetDefaultValue(System.String)
  commentId: M:Sdl.ProjectAutomation.Settings.TranslationCountSettings.GetDefaultValue(System.String)
  id: GetDefaultValue(System.String)
  parent: Sdl.ProjectAutomation.Settings.TranslationCountSettings
  langs:
  - csharp
  - vb
  name: GetDefaultValue(String)
  nameWithType: TranslationCountSettings.GetDefaultValue(String)
  fullName: Sdl.ProjectAutomation.Settings.TranslationCountSettings.GetDefaultValue(System.String)
  type: Method
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the default value.\n"
  syntax:
    content: protected override object GetDefaultValue(string settingId)
    parameters:
    - id: settingId
      type: System.String
      description: The setting id.
    return:
      type: System.Object
      description: The default value.
    content.vb: Protected Overrides Function GetDefaultValue(settingId As String) As Object
  overload: Sdl.ProjectAutomation.Settings.TranslationCountSettings.GetDefaultValue*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Sdl.ProjectAutomation.Settings.TranslationCountSettings.CreateReport
  commentId: P:Sdl.ProjectAutomation.Settings.TranslationCountSettings.CreateReport
  id: CreateReport
  parent: Sdl.ProjectAutomation.Settings.TranslationCountSettings
  langs:
  - csharp
  - vb
  name: CreateReport
  nameWithType: TranslationCountSettings.CreateReport
  fullName: Sdl.ProjectAutomation.Settings.TranslationCountSettings.CreateReport
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the setting that flags whether a report should be generated. Default: <code>true</code>.\n"
  syntax:
    content: public Setting<bool> CreateReport { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property CreateReport As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.TranslationCountSettings.CreateReport*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.TranslationCountSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.TranslationCountSettings.#ctor
  isExternal: true
  name: TranslationCountSettings
  nameWithType: TranslationCountSettings.TranslationCountSettings
  fullName: Sdl.ProjectAutomation.Settings.TranslationCountSettings.TranslationCountSettings
- uid: Sdl.ProjectAutomation.Settings.TranslationCountSettings.GetDefaultValue*
  commentId: Overload:Sdl.ProjectAutomation.Settings.TranslationCountSettings.GetDefaultValue
  isExternal: true
  name: GetDefaultValue
  nameWithType: TranslationCountSettings.GetDefaultValue
  fullName: Sdl.ProjectAutomation.Settings.TranslationCountSettings.GetDefaultValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.TranslationCountSettings.CreateReport*
  commentId: Overload:Sdl.ProjectAutomation.Settings.TranslationCountSettings.CreateReport
  isExternal: true
  name: CreateReport
  nameWithType: TranslationCountSettings.CreateReport
  fullName: Sdl.ProjectAutomation.Settings.TranslationCountSettings.CreateReport
- uid: Sdl.Core.Settings.Setting{System.Boolean}
  commentId: '!:Sdl.Core.Settings.Setting{System.Boolean}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<Boolean>
  nameWithType: Setting<Boolean>
  fullName: Sdl.Core.Settings.Setting<System.Boolean>
  nameWithType.vb: Setting(Of Boolean)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.Boolean)
  name.vb: Setting(Of Boolean)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.Setting`1
  isExternal: true
  name: Setting<>
  nameWithType: Setting<>
  fullName: Sdl.Core.Settings.Setting<>
  nameWithType.vb: Setting(Of )
  fullName.vb: Sdl.Core.Settings.Setting(Of )
  name.vb: Setting(Of )
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
