### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  id: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.BaseMarkupDataType
  - Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.MarkupDataFactory
  - Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.PlaceholderTagMarkup
  - Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.QuickInsertSettings
  - Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.QuickInsertsSettings
  - Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TagPairMarkup
  - Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TextMarkup
  - Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TextPairMarkup
  langs:
  - csharp
  - vb
  name: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  type: Namespace
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.BaseMarkupDataType
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.BaseMarkupDataType
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  isExternal: true
  name: BaseMarkupDataType
  nameWithType: BaseMarkupDataType
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.BaseMarkupDataType
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.MarkupDataFactory
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.MarkupDataFactory
  isExternal: true
  name: MarkupDataFactory
  nameWithType: MarkupDataFactory
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.MarkupDataFactory
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.PlaceholderTagMarkup
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.PlaceholderTagMarkup
  isExternal: true
  name: PlaceholderTagMarkup
  nameWithType: PlaceholderTagMarkup
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.PlaceholderTagMarkup
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.QuickInsertSettings
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.QuickInsertSettings
  isExternal: true
  name: QuickInsertSettings
  nameWithType: QuickInsertSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.QuickInsertSettings
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.QuickInsertsSettings
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.QuickInsertsSettings
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  isExternal: true
  name: QuickInsertsSettings
  nameWithType: QuickInsertsSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.QuickInsertsSettings
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TagPairMarkup
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TagPairMarkup
  isExternal: true
  name: TagPairMarkup
  nameWithType: TagPairMarkup
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TagPairMarkup
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TextMarkup
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TextMarkup
  isExternal: true
  name: TextMarkup
  nameWithType: TextMarkup
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TextMarkup
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TextPairMarkup
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TextPairMarkup
  isExternal: true
  name: TextPairMarkup
  nameWithType: TextPairMarkup
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts.TextPairMarkup
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.QuickInserts
