### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.ExportFileVersion
  commentId: T:Sdl.ProjectAutomation.Settings.ExportFileVersion
  id: ExportFileVersion
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.ExportFileVersion.Bilingual
  - Sdl.ProjectAutomation.Settings.ExportFileVersion.Current
  - Sdl.ProjectAutomation.Settings.ExportFileVersion.Native
  langs:
  - csharp
  - vb
  name: ExportFileVersion
  nameWithType: ExportFileVersion
  fullName: Sdl.ProjectAutomation.Settings.ExportFileVersion
  type: Enum
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nRepresents the possible file versions that can be exported using the Export Files task.\n"
  remarks: The settings for the Export Files task can be specified using the <xref href="Sdl.ProjectAutomation.Settings.ExportFilesSettings" data-throw-if-not-resolved="false"></xref> settings group.
  syntax:
    content: public enum ExportFileVersion
    content.vb: Public Enum ExportFileVersion
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.ProjectAutomation.Settings.ExportFileVersion.Native
  commentId: F:Sdl.ProjectAutomation.Settings.ExportFileVersion.Native
  id: Native
  parent: Sdl.ProjectAutomation.Settings.ExportFileVersion
  langs:
  - csharp
  - vb
  name: Native
  nameWithType: ExportFileVersion.Native
  fullName: Sdl.ProjectAutomation.Settings.ExportFileVersion.Native
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nThe native file verion is exported. For source files, this is the original source file in its original native format, for target files\nit is the generated native target file in its original native format, if it&apos;s available.\n"
  syntax:
    content: Native = 0
    return:
      type: Sdl.ProjectAutomation.Settings.ExportFileVersion
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.ExportFileVersion.Bilingual
  commentId: F:Sdl.ProjectAutomation.Settings.ExportFileVersion.Bilingual
  id: Bilingual
  parent: Sdl.ProjectAutomation.Settings.ExportFileVersion
  langs:
  - csharp
  - vb
  name: Bilingual
  nameWithType: ExportFileVersion.Bilingual
  fullName: Sdl.ProjectAutomation.Settings.ExportFileVersion.Bilingual
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nThe SDLXLIFF file version, if it exists.\n"
  syntax:
    content: Bilingual = 1
    return:
      type: Sdl.ProjectAutomation.Settings.ExportFileVersion
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.ExportFileVersion.Current
  commentId: F:Sdl.ProjectAutomation.Settings.ExportFileVersion.Current
  id: Current
  parent: Sdl.ProjectAutomation.Settings.ExportFileVersion
  langs:
  - csharp
  - vb
  name: Current
  nameWithType: ExportFileVersion.Current
  fullName: Sdl.ProjectAutomation.Settings.ExportFileVersion.Current
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nThe current file version. Depending on which state the file is in, this could be the native or the bilingual (SDLXLIFF) file version.\n"
  syntax:
    content: Current = 2
    return:
      type: Sdl.ProjectAutomation.Settings.ExportFileVersion
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: Sdl.ProjectAutomation.Settings.ExportFileVersion
  commentId: T:Sdl.ProjectAutomation.Settings.ExportFileVersion
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: ExportFileVersion
  nameWithType: ExportFileVersion
  fullName: Sdl.ProjectAutomation.Settings.ExportFileVersion
