### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType
  commentId: T:Sdl.ProjectAutomation.Settings.AppendToUnitType
  id: AppendToUnitType
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.AppendToUnitType.Paragraph
  - Sdl.ProjectAutomation.Settings.AppendToUnitType.Segment
  langs:
  - csharp
  - vb
  name: AppendToUnitType
  nameWithType: AppendToUnitType
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType
  type: Enum
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nTo specify whether <xref href=\"Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString\" data-throw-if-not-resolved=\"false\"></xref> and\n<xref href=\"Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString\" data-throw-if-not-resolved=\"false\"></xref> are applied at the segment or paragraph level.\n"
  syntax:
    content: public enum AppendToUnitType
    content.vb: Public Enum AppendToUnitType
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType.Segment
  commentId: F:Sdl.ProjectAutomation.Settings.AppendToUnitType.Segment
  id: Segment
  parent: Sdl.ProjectAutomation.Settings.AppendToUnitType
  langs:
  - csharp
  - vb
  name: Segment
  nameWithType: AppendToUnitType.Segment
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType.Segment
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nApply <xref href=\"Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString\" data-throw-if-not-resolved=\"false\"></xref> and <xref href=\"Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString\" data-throw-if-not-resolved=\"false\"></xref>\nto each segment\n"
  syntax:
    content: Segment = 0
    return:
      type: Sdl.ProjectAutomation.Settings.AppendToUnitType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType.Paragraph
  commentId: F:Sdl.ProjectAutomation.Settings.AppendToUnitType.Paragraph
  id: Paragraph
  parent: Sdl.ProjectAutomation.Settings.AppendToUnitType
  langs:
  - csharp
  - vb
  name: Paragraph
  nameWithType: AppendToUnitType.Paragraph
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType.Paragraph
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nApply <xref href=\"Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString\" data-throw-if-not-resolved=\"false\"></xref> and <xref href=\"Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString\" data-throw-if-not-resolved=\"false\"></xref>\nto each paragraph (not each segment)\n"
  syntax:
    content: Paragraph = 1
    return:
      type: Sdl.ProjectAutomation.Settings.AppendToUnitType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType
  commentId: T:Sdl.ProjectAutomation.Settings.AppendToUnitType
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: AppendToUnitType
  nameWithType: AppendToUnitType
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType
