### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.ProjectSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ProjectSettings
  id: ProjectSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.ProjectSettings.#ctor
  - Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectIconPath
  - Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectOrigin
  langs:
  - csharp
  - vb
  name: ProjectSettings
  nameWithType: ProjectSettings
  fullName: Sdl.ProjectAutomation.Settings.ProjectSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSettings group, indicating project origin and icon path\n"
  syntax:
    content: 'public class ProjectSettings : SettingsGroup'
    content.vb: >-
      Public Class ProjectSettings

          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.ProjectSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.ProjectSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.ProjectSettings
  langs:
  - csharp
  - vb
  name: ProjectSettings()
  nameWithType: ProjectSettings.ProjectSettings()
  fullName: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  syntax:
    content: public ProjectSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.ProjectSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectOrigin
  commentId: P:Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectOrigin
  id: ProjectOrigin
  parent: Sdl.ProjectAutomation.Settings.ProjectSettings
  langs:
  - csharp
  - vb
  name: ProjectOrigin
  nameWithType: ProjectSettings.ProjectOrigin
  fullName: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectOrigin
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSetting for project origin\n"
  syntax:
    content: public string ProjectOrigin { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ProjectOrigin As String
  overload: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectOrigin*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectIconPath
  commentId: P:Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectIconPath
  id: ProjectIconPath
  parent: Sdl.ProjectAutomation.Settings.ProjectSettings
  langs:
  - csharp
  - vb
  name: ProjectIconPath
  nameWithType: ProjectSettings.ProjectIconPath
  fullName: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectIconPath
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSetting for icon path\n"
  syntax:
    content: public string ProjectIconPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ProjectIconPath As String
  overload: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectIconPath*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.ProjectSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectSettings.#ctor
  isExternal: true
  name: ProjectSettings
  nameWithType: ProjectSettings.ProjectSettings
  fullName: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectSettings
- uid: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectOrigin*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectOrigin
  isExternal: true
  name: ProjectOrigin
  nameWithType: ProjectSettings.ProjectOrigin
  fullName: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectOrigin
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectIconPath*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectIconPath
  isExternal: true
  name: ProjectIconPath
  nameWithType: ProjectSettings.ProjectIconPath
  fullName: Sdl.ProjectAutomation.Settings.ProjectSettings.ProjectIconPath
