### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  id: ImportFromReviewTaskSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.#ctor
  - Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.Backup
  - Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ConfirmationLevel
  - Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ExternalReviewMappingItems
  - Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.GetDefaultValue(System.String)
  langs:
  - csharp
  - vb
  name: ImportFromReviewTaskSettings
  nameWithType: ImportFromReviewTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSettings for importing external review file(s)\n"
  syntax:
    content: 'public class ImportFromReviewTaskSettings : SettingsGroup'
    content.vb: >-
      Public Class ImportFromReviewTaskSettings

          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.GetDefaultValue(System.String)
  commentId: M:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.GetDefaultValue(System.String)
  id: GetDefaultValue(System.String)
  parent: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  langs:
  - csharp
  - vb
  name: GetDefaultValue(String)
  nameWithType: ImportFromReviewTaskSettings.GetDefaultValue(String)
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.GetDefaultValue(System.String)
  type: Method
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the default value.\n"
  syntax:
    content: protected override object GetDefaultValue(string settingId)
    parameters:
    - id: settingId
      type: System.String
      description: The setting id.
    return:
      type: System.Object
    content.vb: Protected Overrides Function GetDefaultValue(settingId As String) As Object
  overload: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.GetDefaultValue*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  langs:
  - csharp
  - vb
  name: ImportFromReviewTaskSettings()
  nameWithType: ImportFromReviewTaskSettings.ImportFromReviewTaskSettings()
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ImportFromReviewTaskSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  syntax:
    content: public ImportFromReviewTaskSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ExternalReviewMappingItems
  commentId: P:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ExternalReviewMappingItems
  id: ExternalReviewMappingItems
  parent: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  langs:
  - csharp
  - vb
  name: ExternalReviewMappingItems
  nameWithType: ImportFromReviewTaskSettings.ExternalReviewMappingItems
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ExternalReviewMappingItems
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nThe xliff files and the corresponding review files mapping\n"
  syntax:
    content: public Setting<List<ExternalReviewMappingItem>> ExternalReviewMappingItems { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Collections.Generic.List{Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem}}
    content.vb: Public ReadOnly Property ExternalReviewMappingItems As Setting(Of List(Of ExternalReviewMappingItem))
  overload: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ExternalReviewMappingItems*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.Backup
  commentId: P:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.Backup
  id: Backup
  parent: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  langs:
  - csharp
  - vb
  name: Backup
  nameWithType: ImportFromReviewTaskSettings.Backup
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.Backup
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nTo decide if the original xliff file should be backuped before importing the review content\n"
  syntax:
    content: public Setting<bool> Backup { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property Backup As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.Backup*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ConfirmationLevel
  commentId: P:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ConfirmationLevel
  id: ConfirmationLevel
  parent: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  langs:
  - csharp
  - vb
  name: ConfirmationLevel
  nameWithType: ImportFromReviewTaskSettings.ConfirmationLevel
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ConfirmationLevel
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nThe segment confirmation level after applying the review changes\n"
  syntax:
    content: public Setting<ConfirmationLevel> ConfirmationLevel { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{Sdl.Core.Globalization.ConfirmationLevel}
    content.vb: Public ReadOnly Property ConfirmationLevel As Setting(Of ConfirmationLevel)
  overload: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ConfirmationLevel*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.GetDefaultValue*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.GetDefaultValue
  isExternal: true
  name: GetDefaultValue
  nameWithType: ImportFromReviewTaskSettings.GetDefaultValue
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.GetDefaultValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.#ctor
  isExternal: true
  name: ImportFromReviewTaskSettings
  nameWithType: ImportFromReviewTaskSettings.ImportFromReviewTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ImportFromReviewTaskSettings
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ExternalReviewMappingItems*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ExternalReviewMappingItems
  isExternal: true
  name: ExternalReviewMappingItems
  nameWithType: ImportFromReviewTaskSettings.ExternalReviewMappingItems
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ExternalReviewMappingItems
- uid: Sdl.Core.Settings.Setting{System.Collections.Generic.List{Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem}}
  commentId: '!:Sdl.Core.Settings.Setting{System.Collections.Generic.List{Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem}}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<List<ExternalReviewMappingItem>>
  nameWithType: Setting<List<ExternalReviewMappingItem>>
  fullName: Sdl.Core.Settings.Setting<System.Collections.Generic.List<Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem>>
  nameWithType.vb: Setting(Of List(Of ExternalReviewMappingItem))
  fullName.vb: Sdl.Core.Settings.Setting(Of System.Collections.Generic.List(Of Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem))
  name.vb: Setting(Of List(Of ExternalReviewMappingItem))
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem
    name: ExternalReviewMappingItem
    nameWithType: ExternalReviewMappingItem
    fullName: Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem
    name: ExternalReviewMappingItem
    nameWithType: ExternalReviewMappingItem
    fullName: Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.Setting`1
  isExternal: true
  name: Setting<>
  nameWithType: Setting<>
  fullName: Sdl.Core.Settings.Setting<>
  nameWithType.vb: Setting(Of )
  fullName.vb: Sdl.Core.Settings.Setting(Of )
  name.vb: Setting(Of )
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.Backup*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.Backup
  isExternal: true
  name: Backup
  nameWithType: ImportFromReviewTaskSettings.Backup
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.Backup
- uid: Sdl.Core.Settings.Setting{System.Boolean}
  commentId: '!:Sdl.Core.Settings.Setting{System.Boolean}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<Boolean>
  nameWithType: Setting<Boolean>
  fullName: Sdl.Core.Settings.Setting<System.Boolean>
  nameWithType.vb: Setting(Of Boolean)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.Boolean)
  name.vb: Setting(Of Boolean)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ConfirmationLevel*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ConfirmationLevel
  isExternal: true
  name: ConfirmationLevel
  nameWithType: ImportFromReviewTaskSettings.ConfirmationLevel
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings.ConfirmationLevel
- uid: Sdl.Core.Settings.Setting{Sdl.Core.Globalization.ConfirmationLevel}
  commentId: '!:Sdl.Core.Settings.Setting{Sdl.Core.Globalization.ConfirmationLevel}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<ConfirmationLevel>
  nameWithType: Setting<ConfirmationLevel>
  fullName: Sdl.Core.Settings.Setting<Sdl.Core.Globalization.ConfirmationLevel>
  nameWithType.vb: Setting(Of ConfirmationLevel)
  fullName.vb: Sdl.Core.Settings.Setting(Of Sdl.Core.Globalization.ConfirmationLevel)
  name.vb: Setting(Of ConfirmationLevel)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Sdl.Core.Globalization.ConfirmationLevel
    name: ConfirmationLevel
    nameWithType: ConfirmationLevel
    fullName: Sdl.Core.Globalization.ConfirmationLevel
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Sdl.Core.Globalization.ConfirmationLevel
    name: ConfirmationLevel
    nameWithType: ConfirmationLevel
    fullName: Sdl.Core.Globalization.ConfirmationLevel
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
