### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  id: AnalysisTaskSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.#ctor
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.CreateReport
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportFrequentSegments
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportUnknownSegments
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.GetDefaultValue(System.String)
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportCrossFileRepetitions
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue
  langs:
  - csharp
  - vb
  name: AnalysisTaskSettings
  nameWithType: AnalysisTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSettings group class for the Analysis automatic task settings.\n"
  syntax:
    content: 'public class AnalysisTaskSettings : SettingsGroup'
    content.vb: >-
      Public Class AnalysisTaskSettings

          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: AnalysisTaskSettings()
  nameWithType: AnalysisTaskSettings.AnalysisTaskSettings()
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.AnalysisTaskSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nDefault constructor. You should never create this object manually. Use <xref href=\"Sdl.Core.Settings.ISettingsBundle.GetSettingsGroup(System.String)\" data-throw-if-not-resolved=\"false\"></xref> instead.\n"
  syntax:
    content: public AnalysisTaskSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.GetDefaultValue(System.String)
  commentId: M:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.GetDefaultValue(System.String)
  id: GetDefaultValue(System.String)
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: GetDefaultValue(String)
  nameWithType: AnalysisTaskSettings.GetDefaultValue(String)
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.GetDefaultValue(System.String)
  type: Method
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the default value.\n"
  syntax:
    content: protected override object GetDefaultValue(string settingId)
    parameters:
    - id: settingId
      type: System.String
      description: The setting id.
    return:
      type: System.Object
      description: The default value.
    content.vb: Protected Overrides Function GetDefaultValue(settingId As String) As Object
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.GetDefaultValue*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.CreateReport
  commentId: P:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.CreateReport
  id: CreateReport
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: CreateReport
  nameWithType: AnalysisTaskSettings.CreateReport
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.CreateReport
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the setting that flags whether a report should be generated. Default: <code>true</code>.\n"
  syntax:
    content: public Setting<bool> CreateReport { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property CreateReport As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.CreateReport*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportFrequentSegments
  commentId: P:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportFrequentSegments
  id: ExportFrequentSegments
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: ExportFrequentSegments
  nameWithType: AnalysisTaskSettings.ExportFrequentSegments
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportFrequentSegments
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the setting that flags whether frequent segments should be exported. Default: <code>false</code>.\n"
  syntax:
    content: public Setting<bool> ExportFrequentSegments { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property ExportFrequentSegments As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportFrequentSegments*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences
  commentId: P:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences
  id: FrequentSegmentsNoOfOccurrences
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: FrequentSegmentsNoOfOccurrences
  nameWithType: AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the settings that states the number of times a segment must be repeated before it is considered a frequent segments. Default: 5.\n"
  syntax:
    content: public Setting<int> FrequentSegmentsNoOfOccurrences { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Int32}
    content.vb: Public ReadOnly Property FrequentSegmentsNoOfOccurrences As Setting(Of Integer)
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportUnknownSegments
  commentId: P:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportUnknownSegments
  id: ExportUnknownSegments
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: ExportUnknownSegments
  nameWithType: AnalysisTaskSettings.ExportUnknownSegments
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportUnknownSegments
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the setting that flags whether unknown segments should be exported. Default: <code>false</code>;\n"
  syntax:
    content: public Setting<bool> ExportUnknownSegments { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property ExportUnknownSegments As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportUnknownSegments*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue
  commentId: P:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue
  id: UnknownSegmentsMaximumMatchValue
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: UnknownSegmentsMaximumMatchValue
  nameWithType: AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the settings that states the maximum match value for a segment to considered an unknown segment. Default: 75.\n"
  syntax:
    content: public Setting<int> UnknownSegmentsMaximumMatchValue { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Int32}
    content.vb: Public ReadOnly Property UnknownSegmentsMaximumMatchValue As Setting(Of Integer)
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportCrossFileRepetitions
  commentId: P:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportCrossFileRepetitions
  id: ReportCrossFileRepetitions
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: ReportCrossFileRepetitions
  nameWithType: AnalysisTaskSettings.ReportCrossFileRepetitions
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportCrossFileRepetitions
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the settings that states whether the analysis process will count cross-file repetitions. Default: True.\n"
  syntax:
    content: public Setting<bool> ReportCrossFileRepetitions { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property ReportCrossFileRepetitions As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportCrossFileRepetitions*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage
  commentId: P:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage
  id: ReportInternalFuzzyMatchLeverage
  parent: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  langs:
  - csharp
  - vb
  name: ReportInternalFuzzyMatchLeverage
  nameWithType: AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the settings that states whether the analysis process will count internal fuzzy matches. Default: False.\n"
  syntax:
    content: public Setting<bool> ReportInternalFuzzyMatchLeverage { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property ReportInternalFuzzyMatchLeverage As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.#ctor
  isExternal: true
  name: AnalysisTaskSettings
  nameWithType: AnalysisTaskSettings.AnalysisTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.AnalysisTaskSettings
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.GetDefaultValue*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.GetDefaultValue
  isExternal: true
  name: GetDefaultValue
  nameWithType: AnalysisTaskSettings.GetDefaultValue
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.GetDefaultValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.CreateReport*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.CreateReport
  isExternal: true
  name: CreateReport
  nameWithType: AnalysisTaskSettings.CreateReport
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.CreateReport
- uid: Sdl.Core.Settings.Setting{System.Boolean}
  commentId: '!:Sdl.Core.Settings.Setting{System.Boolean}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<Boolean>
  nameWithType: Setting<Boolean>
  fullName: Sdl.Core.Settings.Setting<System.Boolean>
  nameWithType.vb: Setting(Of Boolean)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.Boolean)
  name.vb: Setting(Of Boolean)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.Setting`1
  isExternal: true
  name: Setting<>
  nameWithType: Setting<>
  fullName: Sdl.Core.Settings.Setting<>
  nameWithType.vb: Setting(Of )
  fullName.vb: Sdl.Core.Settings.Setting(Of )
  name.vb: Setting(Of )
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportFrequentSegments*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportFrequentSegments
  isExternal: true
  name: ExportFrequentSegments
  nameWithType: AnalysisTaskSettings.ExportFrequentSegments
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportFrequentSegments
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences
  isExternal: true
  name: FrequentSegmentsNoOfOccurrences
  nameWithType: AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.FrequentSegmentsNoOfOccurrences
- uid: Sdl.Core.Settings.Setting{System.Int32}
  commentId: '!:Sdl.Core.Settings.Setting{System.Int32}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<Int32>
  nameWithType: Setting<Int32>
  fullName: Sdl.Core.Settings.Setting<System.Int32>
  nameWithType.vb: Setting(Of Int32)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.Int32)
  name.vb: Setting(Of Int32)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportUnknownSegments*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportUnknownSegments
  isExternal: true
  name: ExportUnknownSegments
  nameWithType: AnalysisTaskSettings.ExportUnknownSegments
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ExportUnknownSegments
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue
  isExternal: true
  name: UnknownSegmentsMaximumMatchValue
  nameWithType: AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.UnknownSegmentsMaximumMatchValue
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportCrossFileRepetitions*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportCrossFileRepetitions
  isExternal: true
  name: ReportCrossFileRepetitions
  nameWithType: AnalysisTaskSettings.ReportCrossFileRepetitions
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportCrossFileRepetitions
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage
  isExternal: true
  name: ReportInternalFuzzyMatchLeverage
  nameWithType: AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings.ReportInternalFuzzyMatchLeverage
