### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  id: ISerializableListItem
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.ClearListItemSettings(Sdl.Core.Settings.ISettingsGroup,System.String)
  - Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.PopulateFromSettingsGroup(Sdl.Core.Settings.ISettingsGroup,System.String)
  - Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.SaveToSettingsGroup(Sdl.Core.Settings.ISettingsGroup,System.String)
  langs:
  - csharp
  - vb
  name: ISerializableListItem
  nameWithType: ISerializableListItem
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nInterface that provides complicated list items in an <xref href=\"Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601\" data-throw-if-not-resolved=\"false\"></xref> with the opportunity\nto serialize and restore themselves when <xref href=\"Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601.SaveToSettingsGroup(Sdl.Core.Settings.ISettingsGroup%2cSystem.String)\" data-throw-if-not-resolved=\"false\"></xref> and\n<xref href=\"Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601.PopulateFromSettingsGroup(Sdl.Core.Settings.ISettingsGroup%2cSystem.String)\" data-throw-if-not-resolved=\"false\"></xref> are called on the parent list.\n"
  remarks: "\nIt is not required to always inherit from this interface when adding an item to <code>ObservableList</code> but\nit is the recommended approach when the item added is of a complex nature (for example, it is another list itself).\n"
  syntax:
    content: public interface ISerializableListItem
    content.vb: Public Interface ISerializableListItem
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.SaveToSettingsGroup(Sdl.Core.Settings.ISettingsGroup,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.SaveToSettingsGroup(Sdl.Core.Settings.ISettingsGroup,System.String)
  id: SaveToSettingsGroup(Sdl.Core.Settings.ISettingsGroup,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  langs:
  - csharp
  - vb
  name: SaveToSettingsGroup(ISettingsGroup, String)
  nameWithType: ISerializableListItem.SaveToSettingsGroup(ISettingsGroup, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.SaveToSettingsGroup(Sdl.Core.Settings.ISettingsGroup, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nSerializes and saves the list item to the settings group.\n"
  syntax:
    content: void SaveToSettingsGroup(ISettingsGroup settingsGroup, string listItemSetting)
    parameters:
    - id: settingsGroup
      type: Sdl.Core.Settings.ISettingsGroup
      description: The settings group of the <xref href="Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601" data-throw-if-not-resolved="false"></xref> that this item belongs to.
    - id: listItemSetting
      type: System.String
      description: The setting ID used by the <xref href="Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601" data-throw-if-not-resolved="false"></xref> to save the list settings.
    content.vb: Sub SaveToSettingsGroup(settingsGroup As ISettingsGroup, listItemSetting As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.SaveToSettingsGroup*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.PopulateFromSettingsGroup(Sdl.Core.Settings.ISettingsGroup,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.PopulateFromSettingsGroup(Sdl.Core.Settings.ISettingsGroup,System.String)
  id: PopulateFromSettingsGroup(Sdl.Core.Settings.ISettingsGroup,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  langs:
  - csharp
  - vb
  name: PopulateFromSettingsGroup(ISettingsGroup, String)
  nameWithType: ISerializableListItem.PopulateFromSettingsGroup(ISettingsGroup, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.PopulateFromSettingsGroup(Sdl.Core.Settings.ISettingsGroup, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nDeserializes and re-populates the list item from the settings group.\n"
  syntax:
    content: void PopulateFromSettingsGroup(ISettingsGroup settingsGroup, string listItemSetting)
    parameters:
    - id: settingsGroup
      type: Sdl.Core.Settings.ISettingsGroup
      description: The settings group of the <xref href="Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601" data-throw-if-not-resolved="false"></xref> that this item belongs to.
    - id: listItemSetting
      type: System.String
      description: The setting ID used by the <xref href="Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601" data-throw-if-not-resolved="false"></xref> to load the list settings.
    content.vb: Sub PopulateFromSettingsGroup(settingsGroup As ISettingsGroup, listItemSetting As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.PopulateFromSettingsGroup*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.ClearListItemSettings(Sdl.Core.Settings.ISettingsGroup,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.ClearListItemSettings(Sdl.Core.Settings.ISettingsGroup,System.String)
  id: ClearListItemSettings(Sdl.Core.Settings.ISettingsGroup,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  langs:
  - csharp
  - vb
  name: ClearListItemSettings(ISettingsGroup, String)
  nameWithType: ISerializableListItem.ClearListItemSettings(ISettingsGroup, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.ClearListItemSettings(Sdl.Core.Settings.ISettingsGroup, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nRemoves all current settings belonging to this list item from the settings bundle. This is called from\n<xref href=\"Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601.SaveToSettingsGroup(Sdl.Core.Settings.ISettingsGroup%2cSystem.String)\" data-throw-if-not-resolved=\"false\"></xref> to ensure that all list items in the settings are removed from\nthe stored list before saving a new set of list items. Implementations may be required if the settings object \nis of a complex type such as another list, otherwise this can be left empty.\n"
  syntax:
    content: void ClearListItemSettings(ISettingsGroup settingsGroup, string listItemSetting)
    parameters:
    - id: settingsGroup
      type: Sdl.Core.Settings.ISettingsGroup
      description: The settings group of the <xref href="Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601" data-throw-if-not-resolved="false"></xref> that this item belongs to.
    - id: listItemSetting
      type: System.String
      description: The setting ID used by the <xref href="Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList%601" data-throw-if-not-resolved="false"></xref> to access the list settings.
    content.vb: Sub ClearListItemSettings(settingsGroup As ISettingsGroup, listItemSetting As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.ClearListItemSettings*
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.SaveToSettingsGroup*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.SaveToSettingsGroup
  isExternal: true
  name: SaveToSettingsGroup
  nameWithType: ISerializableListItem.SaveToSettingsGroup
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.SaveToSettingsGroup
- uid: Sdl.Core.Settings.ISettingsGroup
  isExternal: true
  name: ISettingsGroup
  nameWithType: ISettingsGroup
  fullName: Sdl.Core.Settings.ISettingsGroup
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.PopulateFromSettingsGroup*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.PopulateFromSettingsGroup
  isExternal: true
  name: PopulateFromSettingsGroup
  nameWithType: ISerializableListItem.PopulateFromSettingsGroup
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.PopulateFromSettingsGroup
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.ClearListItemSettings*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.ClearListItemSettings
  isExternal: true
  name: ClearListItemSettings
  nameWithType: ISerializableListItem.ClearListItemSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem.ClearListItemSettings
