### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  id: Sdl.FileTypeSupport.Framework.Core.Settings
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage`2
  - Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList`1
  - Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  - Sdl.FileTypeSupport.Framework.Core.Settings.FileSerializer
  - Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsBase
  - Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  - Sdl.FileTypeSupport.Framework.Core.Settings.FontMappingRule
  - Sdl.FileTypeSupport.Framework.Core.Settings.FontMappingSettings
  - Sdl.FileTypeSupport.Framework.Core.Settings.FormattingGroupSettings
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  - Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeConfigurationAware
  - Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware`1
  - Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  - Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsPage
  - Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  - Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary`2
  - Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList`1
  langs:
  - csharp
  - vb
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
  type: Namespace
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage`2
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage`2
  isExternal: true
  name: AbstractFileTypeSettingsPage<SettingsControlType, SettingsType>
  nameWithType: AbstractFileTypeSettingsPage<SettingsControlType, SettingsType>
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage<SettingsControlType, SettingsType>
  nameWithType.vb: AbstractFileTypeSettingsPage(Of SettingsControlType, SettingsType)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage(Of SettingsControlType, SettingsType)
  name.vb: AbstractFileTypeSettingsPage(Of SettingsControlType, SettingsType)
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage`2
    name: AbstractFileTypeSettingsPage
    nameWithType: AbstractFileTypeSettingsPage
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: SettingsControlType
    nameWithType: SettingsControlType
    fullName: SettingsControlType
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: SettingsType
    nameWithType: SettingsType
    fullName: SettingsType
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage`2
    name: AbstractFileTypeSettingsPage
    nameWithType: AbstractFileTypeSettingsPage
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.AbstractFileTypeSettingsPage
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: SettingsControlType
    nameWithType: SettingsControlType
    fullName: SettingsControlType
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: SettingsType
    nameWithType: SettingsType
    fullName: SettingsType
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList`1
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList`1
  isExternal: true
  name: ComplexObservableList<T>
  nameWithType: ComplexObservableList<T>
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList<T>
  nameWithType.vb: ComplexObservableList(Of T)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList(Of T)
  name.vb: ComplexObservableList(Of T)
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList`1
    name: ComplexObservableList
    nameWithType: ComplexObservableList
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList`1
    name: ComplexObservableList
    nameWithType: ComplexObservableList
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ComplexObservableList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileSerializer
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.FileSerializer
  isExternal: true
  name: FileSerializer
  nameWithType: FileSerializer
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileSerializer
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: DeserializeFileInfo
  nameWithType: DeserializeFileInfo
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsBase
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsBase
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: FileTypeSettingsBase
  nameWithType: FileTypeSettingsBase
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsBase
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  isExternal: true
  name: FileTypeSettingsPageAttribute
  nameWithType: FileTypeSettingsPageAttribute
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FontMappingRule
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.FontMappingRule
  isExternal: true
  name: FontMappingRule
  nameWithType: FontMappingRule
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FontMappingRule
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FontMappingSettings
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.FontMappingSettings
  isExternal: true
  name: FontMappingSettings
  nameWithType: FontMappingSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FontMappingSettings
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FormattingGroupSettings
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.FormattingGroupSettings
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: FormattingGroupSettings
  nameWithType: FormattingGroupSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FormattingGroupSettings
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: IAbstractSettingsPage
  nameWithType: IAbstractSettingsPage
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeConfigurationAware
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeConfigurationAware
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: IFileTypeConfigurationAware
  nameWithType: IFileTypeConfigurationAware
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeConfigurationAware
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware`1
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware`1
  isExternal: true
  name: IFileTypeSettingsAware<SettingsType>
  nameWithType: IFileTypeSettingsAware<SettingsType>
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware<SettingsType>
  nameWithType.vb: IFileTypeSettingsAware(Of SettingsType)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware(Of SettingsType)
  name.vb: IFileTypeSettingsAware(Of SettingsType)
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware`1
    name: IFileTypeSettingsAware
    nameWithType: IFileTypeSettingsAware
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: SettingsType
    nameWithType: SettingsType
    fullName: SettingsType
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware`1
    name: IFileTypeSettingsAware
    nameWithType: IFileTypeSettingsAware
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsAware
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: SettingsType
    nameWithType: SettingsType
    fullName: SettingsType
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: IFileTypeSettingsConverter
  nameWithType: IFileTypeSettingsConverter
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsPage
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsPage
  isExternal: true
  name: IFileTypeSettingsPage
  nameWithType: IFileTypeSettingsPage
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsPage
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: ISerializableListItem
  nameWithType: ISerializableListItem
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ISerializableListItem
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary`2
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary`2
  isExternal: true
  name: ObservableDictionary<TKey, TValue>
  nameWithType: ObservableDictionary<TKey, TValue>
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary<TKey, TValue>
  nameWithType.vb: ObservableDictionary(Of TKey, TValue)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary(Of TKey, TValue)
  name.vb: ObservableDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary`2
    name: ObservableDictionary
    nameWithType: ObservableDictionary
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary`2
    name: ObservableDictionary
    nameWithType: ObservableDictionary
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableDictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList`1
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList`1
  isExternal: true
  name: ObservableList<T>
  nameWithType: ObservableList<T>
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList<T>
  nameWithType.vb: ObservableList(Of T)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList(Of T)
  name.vb: ObservableList(Of T)
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList`1
    name: ObservableList
    nameWithType: ObservableList
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList`1
    name: ObservableList
    nameWithType: ObservableList
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.ObservableList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
