### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider
  id: IDefaultFileTypeSettingsProvider
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  children:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle(Sdl.Core.Settings.ISettingsBundle,System.String)
  langs:
  - csharp
  - vb
  name: IDefaultFileTypeSettingsProvider
  nameWithType: IDefaultFileTypeSettingsProvider
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nInterface representing a file type able to pass all its default settings to outside callers.\n"
  syntax:
    content: public interface IDefaultFileTypeSettingsProvider
    content.vb: Public Interface IDefaultFileTypeSettingsProvider
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle(Sdl.Core.Settings.ISettingsBundle,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle(Sdl.Core.Settings.ISettingsBundle,System.String)
  id: PopulateDefaultSettingsBundle(Sdl.Core.Settings.ISettingsBundle,System.String)
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider
  langs:
  - csharp
  - vb
  name: PopulateDefaultSettingsBundle(ISettingsBundle, String)
  nameWithType: IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle(ISettingsBundle, String)
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle(Sdl.Core.Settings.ISettingsBundle, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nPopulates a given settings bundle with all the default settings used by the file type.\nEach setting must be stored with its explicit default value.\n"
  syntax:
    content: void PopulateDefaultSettingsBundle(ISettingsBundle settingsBundle, string fileTypeConfigurationId)
    parameters:
    - id: settingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
      description: The settings bundle to populate with the default values.
    - id: fileTypeConfigurationId
      type: System.String
      description: Id for the settings group that file type specific settings should be stored in.
    content.vb: Sub PopulateDefaultSettingsBundle(settingsBundle As ISettingsBundle, fileTypeConfigurationId As String)
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle*
references:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle
  isExternal: true
  name: PopulateDefaultSettingsBundle
  nameWithType: IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IDefaultFileTypeSettingsProvider.PopulateDefaultSettingsBundle
- uid: Sdl.Core.Settings.ISettingsBundle
  isExternal: true
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
