### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Constants
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.Constants
  id: Sdl.FileTypeSupport.Framework.Core.Settings.Constants
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.Constants.EncodingConstants
  - Sdl.FileTypeSupport.Framework.Core.Settings.Constants.SettingsConstants
  langs:
  - csharp
  - vb
  name: Sdl.FileTypeSupport.Framework.Core.Settings.Constants
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.Constants
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Constants
  type: Namespace
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Constants.EncodingConstants
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Constants.EncodingConstants
  isExternal: true
  name: EncodingConstants
  nameWithType: EncodingConstants
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Constants.EncodingConstants
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Constants.SettingsConstants
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Constants.SettingsConstants
  isExternal: true
  name: SettingsConstants
  nameWithType: SettingsConstants
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Constants.SettingsConstants
