### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.AbstractTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.AbstractTaskSettings
  id: AbstractTaskSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.AbstractTaskSettings.#ctor
  langs:
  - csharp
  - vb
  name: AbstractTaskSettings
  nameWithType: AbstractTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.AbstractTaskSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nBase class of TaskSettings\n"
  syntax:
    content: 'public abstract class AbstractTaskSettings : SettingsGroup'
    content.vb: >-
      Public MustInherit Class AbstractTaskSettings

          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: Sdl.ProjectAutomation.Settings.AbstractTaskSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.AbstractTaskSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.AbstractTaskSettings
  langs:
  - csharp
  - vb
  name: AbstractTaskSettings()
  nameWithType: AbstractTaskSettings.AbstractTaskSettings()
  fullName: Sdl.ProjectAutomation.Settings.AbstractTaskSettings.AbstractTaskSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  syntax:
    content: protected AbstractTaskSettings()
    content.vb: Protected Sub New
  overload: Sdl.ProjectAutomation.Settings.AbstractTaskSettings.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.AbstractTaskSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.AbstractTaskSettings.#ctor
  isExternal: true
  name: AbstractTaskSettings
  nameWithType: AbstractTaskSettings.AbstractTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.AbstractTaskSettings.AbstractTaskSettings
