### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  id: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.AbstractTaskSettings
  - Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  - Sdl.ProjectAutomation.Settings.AppendToUnitType
  - Sdl.ProjectAutomation.Settings.CreateRegulatorBundleTaskSettings
  - Sdl.ProjectAutomation.Settings.ExportFilesSettings
  - Sdl.ProjectAutomation.Settings.ExportFileVersion
  - Sdl.ProjectAutomation.Settings.ExportForReviewTaskSettings
  - Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem
  - Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  - Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  - Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  - Sdl.ProjectAutomation.Settings.PerfectMatchTaskSettings
  - Sdl.ProjectAutomation.Settings.ProjectSettings
  - Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  - Sdl.ProjectAutomation.Settings.PseudoTranslateSettings
  - Sdl.ProjectAutomation.Settings.ReturningPackageSettings
  - Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  - Sdl.ProjectAutomation.Settings.TmImportOption
  - Sdl.ProjectAutomation.Settings.TranslateTaskSettings
  - Sdl.ProjectAutomation.Settings.TranslationCountSettings
  - Sdl.ProjectAutomation.Settings.TranslationMemorySettings
  - Sdl.ProjectAutomation.Settings.TranslationMemoryUpdateTaskSettings
  - Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  - Sdl.ProjectAutomation.Settings.WordCountSettings
  langs:
  - csharp
  - vb
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
  type: Namespace
  assemblies:
  - Sdl.ProjectAutomation.Settings
references:
- uid: Sdl.ProjectAutomation.Settings.AbstractTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.AbstractTaskSettings
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: AbstractTaskSettings
  nameWithType: AbstractTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.AbstractTaskSettings
- uid: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
  isExternal: true
  name: AnalysisTaskSettings
  nameWithType: AnalysisTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.AnalysisTaskSettings
- uid: Sdl.ProjectAutomation.Settings.CreateRegulatorBundleTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.CreateRegulatorBundleTaskSettings
  isExternal: true
  name: CreateRegulatorBundleTaskSettings
  nameWithType: CreateRegulatorBundleTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.CreateRegulatorBundleTaskSettings
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ExportFilesSettings
  isExternal: true
  name: ExportFilesSettings
  nameWithType: ExportFilesSettings
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings
- uid: Sdl.ProjectAutomation.Settings.ExportFileVersion
  commentId: T:Sdl.ProjectAutomation.Settings.ExportFileVersion
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: ExportFileVersion
  nameWithType: ExportFileVersion
  fullName: Sdl.ProjectAutomation.Settings.ExportFileVersion
- uid: Sdl.ProjectAutomation.Settings.ExportForReviewTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ExportForReviewTaskSettings
  isExternal: true
  name: ExportForReviewTaskSettings
  nameWithType: ExportForReviewTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.ExportForReviewTaskSettings
- uid: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
  isExternal: true
  name: ImportFromReviewTaskSettings
  nameWithType: ImportFromReviewTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.ImportFromReviewTaskSettings
- uid: Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem
  commentId: T:Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem
  isExternal: true
  name: ExternalReviewMappingItem
  nameWithType: ExternalReviewMappingItem
  fullName: Sdl.ProjectAutomation.Settings.ExternalReviewMappingItem
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  commentId: T:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: MeasurementsFormattingMode
  nameWithType: MeasurementsFormattingMode
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
- uid: Sdl.ProjectAutomation.Settings.PerfectMatchTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.PerfectMatchTaskSettings
  isExternal: true
  name: PerfectMatchTaskSettings
  nameWithType: PerfectMatchTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.PerfectMatchTaskSettings
- uid: Sdl.ProjectAutomation.Settings.ProjectSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ProjectSettings
  isExternal: true
  name: ProjectSettings
  nameWithType: ProjectSettings
  fullName: Sdl.ProjectAutomation.Settings.ProjectSettings
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  isExternal: true
  name: ProjectTranslationMemoryTaskSettings
  nameWithType: ProjectTranslationMemoryTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType
  commentId: T:Sdl.ProjectAutomation.Settings.AppendToUnitType
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: AppendToUnitType
  nameWithType: AppendToUnitType
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType
- uid: Sdl.ProjectAutomation.Settings.PseudoTranslateSettings
  commentId: T:Sdl.ProjectAutomation.Settings.PseudoTranslateSettings
  isExternal: true
  name: PseudoTranslateSettings
  nameWithType: PseudoTranslateSettings
  fullName: Sdl.ProjectAutomation.Settings.PseudoTranslateSettings
- uid: Sdl.ProjectAutomation.Settings.ReturningPackageSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ReturningPackageSettings
  isExternal: true
  name: ReturningPackageSettings
  nameWithType: ReturningPackageSettings
  fullName: Sdl.ProjectAutomation.Settings.ReturningPackageSettings
- uid: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  commentId: T:Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: SourceTrackChangesLookupMode
  nameWithType: SourceTrackChangesLookupMode
  fullName: Sdl.ProjectAutomation.Settings.SourceTrackChangesLookupMode
- uid: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  commentId: T:Sdl.ProjectAutomation.Settings.TranslationUpdateMode
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: TranslationUpdateMode
  nameWithType: TranslationUpdateMode
  fullName: Sdl.ProjectAutomation.Settings.TranslationUpdateMode
- uid: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  commentId: T:Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: NoTranslationMemoryMatchFoundAction
  nameWithType: NoTranslationMemoryMatchFoundAction
  fullName: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
- uid: Sdl.ProjectAutomation.Settings.TranslateTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.TranslateTaskSettings
  isExternal: true
  name: TranslateTaskSettings
  nameWithType: TranslateTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.TranslateTaskSettings
- uid: Sdl.ProjectAutomation.Settings.TranslationCountSettings
  commentId: T:Sdl.ProjectAutomation.Settings.TranslationCountSettings
  isExternal: true
  name: TranslationCountSettings
  nameWithType: TranslationCountSettings
  fullName: Sdl.ProjectAutomation.Settings.TranslationCountSettings
- uid: Sdl.ProjectAutomation.Settings.TranslationMemorySettings
  commentId: T:Sdl.ProjectAutomation.Settings.TranslationMemorySettings
  isExternal: true
  name: TranslationMemorySettings
  nameWithType: TranslationMemorySettings
  fullName: Sdl.ProjectAutomation.Settings.TranslationMemorySettings
- uid: Sdl.ProjectAutomation.Settings.TmImportOption
  commentId: T:Sdl.ProjectAutomation.Settings.TmImportOption
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: TmImportOption
  nameWithType: TmImportOption
  fullName: Sdl.ProjectAutomation.Settings.TmImportOption
- uid: Sdl.ProjectAutomation.Settings.TranslationMemoryUpdateTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.TranslationMemoryUpdateTaskSettings
  isExternal: true
  name: TranslationMemoryUpdateTaskSettings
  nameWithType: TranslationMemoryUpdateTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.TranslationMemoryUpdateTaskSettings
- uid: Sdl.ProjectAutomation.Settings.WordCountSettings
  commentId: T:Sdl.ProjectAutomation.Settings.WordCountSettings
  isExternal: true
  name: WordCountSettings
  nameWithType: WordCountSettings
  fullName: Sdl.ProjectAutomation.Settings.WordCountSettings
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
