### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  id: FileTypeSettingsPageAttribute
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor
  - Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor(System.String,System.String,System.String)
  - Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.HelpTopic
  langs:
  - csharp
  - vb
  name: FileTypeSettingsPageAttribute
  nameWithType: FileTypeSettingsPageAttribute
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  type: Class
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nApply this attribute to a class implementing Sdl.Core.Settings.ISettingsPage.\n"
  remarks: "\n<p>\nFile type settings pages typically also implement <xref href=\"Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeConfigurationAware\" data-throw-if-not-resolved=\"false\"></xref>.\n</p>\n"
  syntax:
    content: >-
      [AttributeUsage(AttributeTargets.Class)]

      public class FileTypeSettingsPageAttribute : SortableExtensionAttribute
    content.vb: >-
      <AttributeUsage(AttributeTargets.Class)>

      Public Class FileTypeSettingsPageAttribute
          Inherits SortableExtensionAttribute
  inheritance:
  - System.Object
  attributes:
  - type: System.AttributeUsageAttribute
    ctor: System.AttributeUsageAttribute.#ctor(System.AttributeTargets)
    arguments:
    - type: System.AttributeTargets
      value: 4
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor
  id: '#ctor'
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  langs:
  - csharp
  - vb
  name: FileTypeSettingsPageAttribute()
  nameWithType: FileTypeSettingsPageAttribute.FileTypeSettingsPageAttribute()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.FileTypeSettingsPageAttribute()
  type: Constructor
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nDefault constructor; see base class for documentation.\n"
  syntax:
    content: public FileTypeSettingsPageAttribute()
    content.vb: Public Sub New
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor(System.String,System.String,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  langs:
  - csharp
  - vb
  name: FileTypeSettingsPageAttribute(String, String, String)
  nameWithType: FileTypeSettingsPageAttribute.FileTypeSettingsPageAttribute(String, String, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.FileTypeSettingsPageAttribute(System.String, System.String, System.String)
  type: Constructor
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nConstruct with id, name and description. See base class for parameter documentation.\n"
  syntax:
    content: public FileTypeSettingsPageAttribute(string id, string name, string description)
    parameters:
    - id: id
      type: System.String
    - id: name
      type: System.String
    - id: description
      type: System.String
    content.vb: Public Sub New(id As String, name As String, description As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.HelpTopic
  commentId: P:Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.HelpTopic
  id: HelpTopic
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute
  langs:
  - csharp
  - vb
  name: HelpTopic
  nameWithType: FileTypeSettingsPageAttribute.HelpTopic
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.HelpTopic
  type: Property
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nHelp topic ID associated with the settings page.\n"
  syntax:
    content: public string HelpTopic { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property HelpTopic As String
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.HelpTopic*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.#ctor
  isExternal: true
  name: FileTypeSettingsPageAttribute
  nameWithType: FileTypeSettingsPageAttribute.FileTypeSettingsPageAttribute
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.FileTypeSettingsPageAttribute
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.HelpTopic*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.HelpTopic
  isExternal: true
  name: HelpTopic
  nameWithType: FileTypeSettingsPageAttribute.HelpTopic
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.FileTypeSettingsPageAttribute.HelpTopic
