### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  id: IAbstractSettingsPage
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterCancel
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterSave
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Cancel
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnActivate
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnDeactivate
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save
  - Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput
  langs:
  - csharp
  - vb
  name: IAbstractSettingsPage
  nameWithType: IAbstractSettingsPage
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nThis interface defines the basic communication between a settings\npage and its host.\n"
  remarks: "\n<p>\nThis interface intentionally excludes initialization and user interface\ncomponents, since this tends to be implementation specific. \n</p>\n"
  syntax:
    content: public interface IAbstractSettingsPage
    content.vb: Public Interface IAbstractSettingsPage
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnActivate
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnActivate
  id: OnActivate
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: OnActivate()
  nameWithType: IAbstractSettingsPage.OnActivate()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnActivate()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nCalled when this settings page is activated.\n"
  syntax:
    content: void OnActivate()
    content.vb: Sub OnActivate
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnActivate*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnDeactivate
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnDeactivate
  id: OnDeactivate
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: OnDeactivate()
  nameWithType: IAbstractSettingsPage.OnDeactivate()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnDeactivate()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nCalled when this settings page is deactivated.\n"
  syntax:
    content: void OnDeactivate()
    content.vb: Sub OnDeactivate
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnDeactivate*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput
  id: ValidateInput
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: ValidateInput()
  nameWithType: IAbstractSettingsPage.ValidateInput()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nReturns true if the input on this settings page is valid.\n"
  remarks: This method is called when navigating away from a page and before <xref href="Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save" data-throw-if-not-resolved="false"></xref> is called.
  syntax:
    content: bool ValidateInput()
    return:
      type: System.Boolean
      description: True if the input on this settings page is valid.
    content.vb: Function ValidateInput As Boolean
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save
  id: Save
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: IAbstractSettingsPage.Save()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nCalled when settings should be saved. The implementation is responsible for persisting the settings.\n"
  remarks: This method is called once, after <xref href="Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput" data-throw-if-not-resolved="false"></xref> has been called.
  syntax:
    content: void Save()
    content.vb: Sub Save
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterSave
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterSave
  id: AfterSave
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: AfterSave()
  nameWithType: IAbstractSettingsPage.AfterSave()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterSave()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nCalled after all settings pages shown on the settings dialog have been saved.\n"
  syntax:
    content: void AfterSave()
    content.vb: Sub AfterSave
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterSave*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Cancel
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Cancel
  id: Cancel
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: Cancel()
  nameWithType: IAbstractSettingsPage.Cancel()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Cancel()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nCalled when the settings dialog is canceled.\n"
  syntax:
    content: void Cancel()
    content.vb: Sub Cancel
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Cancel*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterCancel
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterCancel
  id: AfterCancel
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: AfterCancel()
  nameWithType: IAbstractSettingsPage.AfterCancel()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterCancel()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nCalled after all settings pages shown on the settings dialog have been canceled.\n"
  syntax:
    content: void AfterCancel()
    content.vb: Sub AfterCancel
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterCancel*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults
  id: ResetToDefaults
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: ResetToDefaults()
  nameWithType: IAbstractSettingsPage.ResetToDefaults()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nCalled to reset settings to default values. The implementation is responsible for\nresetting the settings and updating the user interface accordingly.\n"
  remarks: "\n<p>\nThis method should not save the settings yet. This should be done in <xref href=\"Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save\" data-throw-if-not-resolved=\"false\"></xref>.\n</p>\n<p>This method will not be called if <xref href=\"Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings\" data-throw-if-not-resolved=\"false\"></xref> returns <code>false</code>.</p>\n"
  syntax:
    content: void ResetToDefaults()
    content.vb: Sub ResetToDefaults
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings
  commentId: P:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings
  id: HasDefaultSettings
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage
  langs:
  - csharp
  - vb
  name: HasDefaultSettings
  nameWithType: IAbstractSettingsPage.HasDefaultSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings
  type: Property
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nCalled to determine whether the settings page supports the <xref href=\"Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults\" data-throw-if-not-resolved=\"false\"></xref> method.\n"
  remarks: "\n<p>\nDetermines whether a &apos;Reset To Default&apos; button should be displayed/enabled in the host application.\n</p>\n"
  syntax:
    content: bool HasDefaultSettings { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasDefaultSettings As Boolean
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnActivate*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnActivate
  isExternal: true
  name: OnActivate
  nameWithType: IAbstractSettingsPage.OnActivate
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnActivate
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnDeactivate*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnDeactivate
  isExternal: true
  name: OnDeactivate
  nameWithType: IAbstractSettingsPage.OnDeactivate
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.OnDeactivate
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput
  isExternal: true
  name: ValidateInput
  nameWithType: IAbstractSettingsPage.ValidateInput
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ValidateInput
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save
  isExternal: true
  name: Save
  nameWithType: IAbstractSettingsPage.Save
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Save
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterSave*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterSave
  isExternal: true
  name: AfterSave
  nameWithType: IAbstractSettingsPage.AfterSave
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterSave
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Cancel*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Cancel
  isExternal: true
  name: Cancel
  nameWithType: IAbstractSettingsPage.Cancel
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.Cancel
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterCancel*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterCancel
  isExternal: true
  name: AfterCancel
  nameWithType: IAbstractSettingsPage.AfterCancel
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.AfterCancel
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults
  isExternal: true
  name: ResetToDefaults
  nameWithType: IAbstractSettingsPage.ResetToDefaults
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.ResetToDefaults
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings
  isExternal: true
  name: HasDefaultSettings
  nameWithType: IAbstractSettingsPage.HasDefaultSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IAbstractSettingsPage.HasDefaultSettings
