### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  id: ISettingsClass
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Read(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter)
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.ResetToDefaults
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Save(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor)
  langs:
  - csharp
  - vb
  name: ISettingsClass
  nameWithType: ISettingsClass
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: 'public interface ISettingsClass : ICloneable, IEquatable<ISettingsClass>'
    content.vb: >-
      Public Interface ISettingsClass
          Inherits ICloneable, IEquatable(Of ISettingsClass)
  inheritedMembers:
  - System.ICloneable.Clone
  - System.IEquatable{Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass}.Equals(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Read(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Read(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter)
  id: Read(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  langs:
  - csharp
  - vb
  name: Read(IValueGetter)
  nameWithType: ISettingsClass.Read(IValueGetter)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Read(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: void Read(IValueGetter valueGetter)
    parameters:
    - id: valueGetter
      type: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter
    content.vb: Sub Read(valueGetter As IValueGetter)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Read*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Save(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Save(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor)
  id: Save(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  langs:
  - csharp
  - vb
  name: Save(IValueProcessor)
  nameWithType: ISettingsClass.Save(IValueProcessor)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Save(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: void Save(IValueProcessor valueProcessor)
    parameters:
    - id: valueProcessor
      type: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor
    content.vb: Sub Save(valueProcessor As IValueProcessor)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Save*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.ResetToDefaults
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.ResetToDefaults
  id: ResetToDefaults
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  langs:
  - csharp
  - vb
  name: ResetToDefaults()
  nameWithType: ISettingsClass.ResetToDefaults()
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.ResetToDefaults()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: void ResetToDefaults()
    content.vb: Sub ResetToDefaults
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.ResetToDefaults*
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
- uid: System.ICloneable.Clone
  commentId: M:System.ICloneable.Clone
  parent: System.ICloneable
  isExternal: true
  name: Clone()
  nameWithType: ICloneable.Clone()
  fullName: System.ICloneable.Clone()
  spec.csharp:
  - uid: System.ICloneable.Clone
    name: Clone
    nameWithType: ICloneable.Clone
    fullName: System.ICloneable.Clone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ICloneable.Clone
    name: Clone
    nameWithType: ICloneable.Clone
    fullName: System.ICloneable.Clone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.IEquatable{Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass}.Equals(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass)
  commentId: M:System.IEquatable{Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass}.Equals(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass)
  parent: System.IEquatable{Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass}
  definition: System.IEquatable`1.Equals(`0)
  name: Equals(ISettingsClass)
  nameWithType: IEquatable<ISettingsClass>.Equals(ISettingsClass)
  fullName: System.IEquatable<Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass>.Equals(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass)
  nameWithType.vb: IEquatable(Of ISettingsClass).Equals(ISettingsClass)
  fullName.vb: System.IEquatable(Of Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass).Equals(Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass)
  spec.csharp:
  - uid: System.IEquatable`1.Equals(`0)
    name: Equals
    nameWithType: IEquatable<ISettingsClass>.Equals
    fullName: System.IEquatable<Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass>.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
    name: ISettingsClass
    nameWithType: ISettingsClass
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.IEquatable`1.Equals(`0)
    name: Equals
    nameWithType: IEquatable(Of ISettingsClass).Equals
    fullName: System.IEquatable(Of Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass).Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
    name: ISettingsClass
    nameWithType: ISettingsClass
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ICloneable
  commentId: T:System.ICloneable
  parent: System
  isExternal: true
  name: ICloneable
  nameWithType: ICloneable
  fullName: System.ICloneable
- uid: System.IEquatable`1.Equals(`0)
  commentId: M:System.IEquatable`1.Equals(`0)
  isExternal: true
  name: Equals(T)
  nameWithType: IEquatable<T>.Equals(T)
  fullName: System.IEquatable<T>.Equals(T)
  nameWithType.vb: IEquatable(Of T).Equals(T)
  fullName.vb: System.IEquatable(Of T).Equals(T)
  spec.csharp:
  - uid: System.IEquatable`1.Equals(`0)
    name: Equals
    nameWithType: IEquatable<T>.Equals
    fullName: System.IEquatable<T>.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.IEquatable`1.Equals(`0)
    name: Equals
    nameWithType: IEquatable(Of T).Equals
    fullName: System.IEquatable(Of T).Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.IEquatable{Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass}
  commentId: T:System.IEquatable{Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass}
  parent: System
  definition: System.IEquatable`1
  name: IEquatable<ISettingsClass>
  nameWithType: IEquatable<ISettingsClass>
  fullName: System.IEquatable<Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass>
  nameWithType.vb: IEquatable(Of ISettingsClass)
  fullName.vb: System.IEquatable(Of Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass)
  name.vb: IEquatable(Of ISettingsClass)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
    name: ISettingsClass
    nameWithType: ISettingsClass
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
    name: ISettingsClass
    nameWithType: ISettingsClass
    fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    nameWithType: IEquatable
    fullName: System.IEquatable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Read*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Read
  isExternal: true
  name: Read
  nameWithType: ISettingsClass.Read
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Read
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  name: IValueGetter
  nameWithType: IValueGetter
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Save*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Save
  isExternal: true
  name: Save
  nameWithType: ISettingsClass.Save
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.Save
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  name: IValueProcessor
  nameWithType: IValueProcessor
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.ResetToDefaults*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.ResetToDefaults
  isExternal: true
  name: ResetToDefaults
  nameWithType: ISettingsClass.ResetToDefaults
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.ResetToDefaults
