### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  id: IApplicationPreviewType
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  children:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  langs:
  - csharp
  - vb
  name: IApplicationPreviewType
  nameWithType: IApplicationPreviewType
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nInterface implemented by preview types that provide a mechanism\nto launch an external application to view the content.\n"
  remarks: "\n<p>\nTwo types of preview applications can be provided: single file and &quot;source and\ntarget&quot; (typically side-by-side). The implementation can provide either\nor both of these.\n</p>\n<p>\nHost applications can check these ids to determine which launch\nbuttons/tabs should be available in the UI for a specific preview type.\n</p>\n"
  syntax:
    content: 'public interface IApplicationPreviewType : IPreviewType'
    content.vb: >-
      Public Interface IApplicationPreviewType
          Inherits IPreviewType
  inheritedMembers:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.SourceGeneratorId
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.TargetGeneratorId
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  id: SingleFilePreviewApplicationId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  langs:
  - csharp
  - vb
  name: SingleFilePreviewApplicationId
  nameWithType: IApplicationPreviewType.SingleFilePreviewApplicationId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  type: Property
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nId for preview application implementation that can be used\nto launch a preview for a single (source or target language) file.\n"
  remarks: "\nThis id can be passed to <xref href=\"Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)\" data-throw-if-not-resolved=\"false\"></xref> to create\nan instance of the application, which should implement <xref href=\"Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  syntax:
    content: PreviewApplicationId? SingleFilePreviewApplicationId { get; set; }
    parameters: []
    return:
      type: System.Nullable{Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId}
    content.vb: Property SingleFilePreviewApplicationId As PreviewApplicationId?
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId*
  modifiers.csharp:
  - get
  - set
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  id: SourceAndTargetPreviewApplicationId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  langs:
  - csharp
  - vb
  name: SourceAndTargetPreviewApplicationId
  nameWithType: IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  type: Property
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nId of the preview application implementation, which can be used\nto launch a preview for both source and target files.\n"
  remarks: "\nThis id can be passed to <xref href=\"Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)\" data-throw-if-not-resolved=\"false\"></xref> in order to create\nan instance of the application, which should implement <xref href=\"Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  syntax:
    content: PreviewApplicationId? SourceAndTargetPreviewApplicationId { get; set; }
    parameters: []
    return:
      type: System.Nullable{Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId}
    content.vb: Property SourceAndTargetPreviewApplicationId As PreviewApplicationId?
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId*
  modifiers.csharp:
  - get
  - set
references:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.SourceGeneratorId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.SourceGeneratorId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
  isExternal: true
  name: SourceGeneratorId
  nameWithType: IPreviewType.SourceGeneratorId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.SourceGeneratorId
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.TargetGeneratorId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.TargetGeneratorId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
  isExternal: true
  name: TargetGeneratorId
  nameWithType: IPreviewType.TargetGeneratorId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.TargetGeneratorId
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  name: IPreviewType
  nameWithType: IPreviewType
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  isExternal: true
  name: SingleFilePreviewApplicationId
  nameWithType: IApplicationPreviewType.SingleFilePreviewApplicationId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
- uid: System.Nullable{Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId}
  commentId: T:System.Nullable{Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId}
  parent: System
  definition: System.Nullable`1
  name: Nullable<PreviewApplicationId>
  nameWithType: Nullable<PreviewApplicationId>
  fullName: System.Nullable<Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId>
  nameWithType.vb: Nullable(Of PreviewApplicationId)
  fullName.vb: System.Nullable(Of Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)
  name.vb: Nullable(Of PreviewApplicationId)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId
    name: PreviewApplicationId
    nameWithType: PreviewApplicationId
    fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId
    name: PreviewApplicationId
    nameWithType: PreviewApplicationId
    fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  isExternal: true
  name: SourceAndTargetPreviewApplicationId
  nameWithType: IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
