### YamlMime:ManagedReference
items:
- uid: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute
  commentId: T:Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute
  id: GlobalVerifierSettingsPageAttribute
  parent: Sdl.Verification.Api
  children:
  - Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.#ctor
  - Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.HelpTopic
  langs:
  - csharp
  - vb
  name: GlobalVerifierSettingsPageAttribute
  nameWithType: GlobalVerifierSettingsPageAttribute
  fullName: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute
  type: Class
  source:
    path: Sdl.Verification.Api
    isExternal: true
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: "\nGlobalVerifierSettingsPageAttribute class represents a global verifier settings page attribute that\nshould be used to mark global verifier settings page classes.\n"
  syntax:
    content: 'public class GlobalVerifierSettingsPageAttribute : ExtensionAttribute'
    content.vb: >-
      Public Class GlobalVerifierSettingsPageAttribute

          Inherits ExtensionAttribute
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.#ctor
  commentId: M:Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.#ctor
  id: '#ctor'
  parent: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute
  langs:
  - csharp
  - vb
  name: GlobalVerifierSettingsPageAttribute()
  nameWithType: GlobalVerifierSettingsPageAttribute.GlobalVerifierSettingsPageAttribute()
  fullName: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.GlobalVerifierSettingsPageAttribute()
  type: Constructor
  source:
    path: Sdl.Verification.Api
    isExternal: true
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: "\nDefault constructor.\n"
  syntax:
    content: public GlobalVerifierSettingsPageAttribute()
    content.vb: Public Sub New
  overload: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.HelpTopic
  commentId: P:Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.HelpTopic
  id: HelpTopic
  parent: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute
  langs:
  - csharp
  - vb
  name: HelpTopic
  nameWithType: GlobalVerifierSettingsPageAttribute.HelpTopic
  fullName: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.HelpTopic
  type: Property
  source:
    path: Sdl.Verification.Api
    isExternal: true
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: "\nHelpTopic property represents the help topic reference for the global verifier settings page.\n"
  syntax:
    content: public string HelpTopic { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property HelpTopic As String
  overload: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.HelpTopic*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.Verification.Api
  commentId: N:Sdl.Verification.Api
  isExternal: true
  name: Sdl.Verification.Api
  nameWithType: Sdl.Verification.Api
  fullName: Sdl.Verification.Api
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.#ctor*
  commentId: Overload:Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.#ctor
  isExternal: true
  name: GlobalVerifierSettingsPageAttribute
  nameWithType: GlobalVerifierSettingsPageAttribute.GlobalVerifierSettingsPageAttribute
  fullName: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.GlobalVerifierSettingsPageAttribute
- uid: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.HelpTopic*
  commentId: Overload:Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.HelpTopic
  isExternal: true
  name: HelpTopic
  nameWithType: GlobalVerifierSettingsPageAttribute.HelpTopic
  fullName: Sdl.Verification.Api.GlobalVerifierSettingsPageAttribute.HelpTopic
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
