### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
  commentId: T:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
  id: SettingsGroupTypeDescriptor
  parent: Sdl.Core.Settings.Implementation
  children:
  - Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.#ctor(Sdl.Core.Settings.SettingsGroup)
  - Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.GetProperties
  langs:
  - csharp
  - vb
  name: SettingsGroupTypeDescriptor
  nameWithType: SettingsGroupTypeDescriptor
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
  type: Class
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  summary: "\nOverrides the implementation of CustomTypeDescriptor\n"
  syntax:
    content: 'public class SettingsGroupTypeDescriptor : CustomTypeDescriptor'
    content.vb: >-
      Public Class SettingsGroupTypeDescriptor
          Inherits CustomTypeDescriptor
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.#ctor(Sdl.Core.Settings.SettingsGroup)
  commentId: M:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.#ctor(Sdl.Core.Settings.SettingsGroup)
  id: '#ctor(Sdl.Core.Settings.SettingsGroup)'
  parent: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
  langs:
  - csharp
  - vb
  name: SettingsGroupTypeDescriptor(SettingsGroup)
  nameWithType: SettingsGroupTypeDescriptor.SettingsGroupTypeDescriptor(SettingsGroup)
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.SettingsGroupTypeDescriptor(Sdl.Core.Settings.SettingsGroup)
  type: Constructor
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  summary: "\nConstructs a SettingsGroupTypeDescriptor using the provided SettingsGroup\n"
  syntax:
    content: public SettingsGroupTypeDescriptor(SettingsGroup settingsGroup)
    parameters:
    - id: settingsGroup
      type: Sdl.Core.Settings.SettingsGroup
      description: the SettingsGroup to use
    content.vb: Public Sub New(settingsGroup As SettingsGroup)
  overload: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.GetProperties
  commentId: M:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.GetProperties
  id: GetProperties
  parent: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor
  langs:
  - csharp
  - vb
  name: GetProperties()
  nameWithType: SettingsGroupTypeDescriptor.GetProperties()
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.GetProperties()
  type: Method
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  summary: "\nReturns a collection of property descriptors for the object represented by this type descriptor.\n"
  syntax:
    content: public override PropertyDescriptorCollection GetProperties()
    return:
      type: System.ComponentModel.PropertyDescriptorCollection
      description: A collection of property descriptors for the object represented by this type descriptor.
    content.vb: Public Overrides Function GetProperties As PropertyDescriptorCollection
  overload: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.GetProperties*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Sdl.Core.Settings.Implementation
  commentId: N:Sdl.Core.Settings.Implementation
  isExternal: true
  name: Sdl.Core.Settings.Implementation
  nameWithType: Sdl.Core.Settings.Implementation
  fullName: Sdl.Core.Settings.Implementation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.#ctor*
  commentId: Overload:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.#ctor
  isExternal: true
  name: SettingsGroupTypeDescriptor
  nameWithType: SettingsGroupTypeDescriptor.SettingsGroupTypeDescriptor
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.SettingsGroupTypeDescriptor
- uid: Sdl.Core.Settings.SettingsGroup
  commentId: T:Sdl.Core.Settings.SettingsGroup
  parent: Sdl.Core.Settings
  isExternal: true
  name: SettingsGroup
  nameWithType: SettingsGroup
  fullName: Sdl.Core.Settings.SettingsGroup
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  isExternal: true
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.GetProperties*
  commentId: Overload:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.GetProperties
  isExternal: true
  name: GetProperties
  nameWithType: SettingsGroupTypeDescriptor.GetProperties
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptor.GetProperties
- uid: System.ComponentModel.PropertyDescriptorCollection
  commentId: '!:System.ComponentModel.PropertyDescriptorCollection'
  isExternal: true
  name: PropertyDescriptorCollection
  nameWithType: PropertyDescriptorCollection
  fullName: System.ComponentModel.PropertyDescriptorCollection
