### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
  commentId: T:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
  id: SettingsGroupTypeDescriptionProvider
  parent: Sdl.Core.Settings.Implementation
  children:
  - Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.#ctor
  - Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.GetTypeDescriptor(System.Type,System.Object)
  langs:
  - csharp
  - vb
  name: SettingsGroupTypeDescriptionProvider
  nameWithType: SettingsGroupTypeDescriptionProvider
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
  type: Class
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  summary: "\nProvides supplemental metadata information for SettingsGroup type\n"
  syntax:
    content: 'public class SettingsGroupTypeDescriptionProvider : TypeDescriptionProvider'
    content.vb: >-
      Public Class SettingsGroupTypeDescriptionProvider
          Inherits TypeDescriptionProvider
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.GetTypeDescriptor(System.Type,System.Object)
  commentId: M:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.GetTypeDescriptor(System.Type,System.Object)
  id: GetTypeDescriptor(System.Type,System.Object)
  parent: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
  langs:
  - csharp
  - vb
  name: GetTypeDescriptor(Type, Object)
  nameWithType: SettingsGroupTypeDescriptionProvider.GetTypeDescriptor(Type, Object)
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.GetTypeDescriptor(System.Type, System.Object)
  type: Method
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  summary: "\nGets a custom type descriptor for the given type and object.\n"
  syntax:
    content: public override ICustomTypeDescriptor GetTypeDescriptor(Type objectType, object instance)
    parameters:
    - id: objectType
      type: System.Type
      description: The type of object for which to retrieve the type descriptor.
    - id: instance
      type: System.Object
      description: An instance of the type. Can be null if no instance was passed to the System.ComponentModel.TypeDescriptor.
    return:
      type: System.ComponentModel.ICustomTypeDescriptor
      description: An System.ComponentModel.ICustomTypeDescriptor that can provide metadata for the type.
    content.vb: Public Overrides Function GetTypeDescriptor(objectType As Type, instance As Object) As ICustomTypeDescriptor
  overload: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.GetTypeDescriptor*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.#ctor
  commentId: M:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.#ctor
  id: '#ctor'
  parent: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider
  langs:
  - csharp
  - vb
  name: SettingsGroupTypeDescriptionProvider()
  nameWithType: SettingsGroupTypeDescriptionProvider.SettingsGroupTypeDescriptionProvider()
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.SettingsGroupTypeDescriptionProvider()
  type: Constructor
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  syntax:
    content: public SettingsGroupTypeDescriptionProvider()
    content.vb: Public Sub New
  overload: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Sdl.Core.Settings.Implementation
  commentId: N:Sdl.Core.Settings.Implementation
  isExternal: true
  name: Sdl.Core.Settings.Implementation
  nameWithType: Sdl.Core.Settings.Implementation
  fullName: Sdl.Core.Settings.Implementation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.GetTypeDescriptor*
  commentId: Overload:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.GetTypeDescriptor
  isExternal: true
  name: GetTypeDescriptor
  nameWithType: SettingsGroupTypeDescriptionProvider.GetTypeDescriptor
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.GetTypeDescriptor
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ComponentModel.ICustomTypeDescriptor
  commentId: '!:System.ComponentModel.ICustomTypeDescriptor'
  isExternal: true
  name: ICustomTypeDescriptor
  nameWithType: ICustomTypeDescriptor
  fullName: System.ComponentModel.ICustomTypeDescriptor
- uid: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.#ctor*
  commentId: Overload:Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.#ctor
  isExternal: true
  name: SettingsGroupTypeDescriptionProvider
  nameWithType: SettingsGroupTypeDescriptionProvider.SettingsGroupTypeDescriptionProvider
  fullName: Sdl.Core.Settings.Implementation.SettingsGroupTypeDescriptionProvider.SettingsGroupTypeDescriptionProvider
