### YamlMime:ManagedReference
items:
- uid: Sdl.Core.PluginFramework.Configuration.ConfigManager
  commentId: T:Sdl.Core.PluginFramework.Configuration.ConfigManager
  id: ConfigManager
  parent: Sdl.Core.PluginFramework.Configuration
  children:
  - Sdl.Core.PluginFramework.Configuration.ConfigManager.#ctor
  - Sdl.Core.PluginFramework.Configuration.ConfigManager.GetDefaultXmlConfiguration
  - Sdl.Core.PluginFramework.Configuration.ConfigManager.GetXmlConfiguration(System.String)
  langs:
  - csharp
  - vb
  name: ConfigManager
  nameWithType: ConfigManager
  fullName: Sdl.Core.PluginFramework.Configuration.ConfigManager
  type: Class
  source:
    path: Sdl.Core.PluginFramework
    isExternal: true
  assemblies:
  - Sdl.Core.PluginFramework
  namespace: Sdl.Core.PluginFramework.Configuration
  syntax:
    content: 'public class ConfigManager : Object'
    content.vb: >-
      Public Class ConfigManager

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetDefaultXmlConfiguration
  commentId: M:Sdl.Core.PluginFramework.Configuration.ConfigManager.GetDefaultXmlConfiguration
  id: GetDefaultXmlConfiguration
  parent: Sdl.Core.PluginFramework.Configuration.ConfigManager
  langs:
  - csharp
  - vb
  name: GetDefaultXmlConfiguration()
  nameWithType: ConfigManager.GetDefaultXmlConfiguration()
  fullName: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetDefaultXmlConfiguration()
  type: Method
  source:
    path: Sdl.Core.PluginFramework
    isExternal: true
  assemblies:
  - Sdl.Core.PluginFramework
  namespace: Sdl.Core.PluginFramework.Configuration
  syntax:
    content: public IFrameworkConfiguration GetDefaultXmlConfiguration()
    return:
      type: Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
    content.vb: Public Function GetDefaultXmlConfiguration As IFrameworkConfiguration
  overload: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetDefaultXmlConfiguration*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetXmlConfiguration(System.String)
  commentId: M:Sdl.Core.PluginFramework.Configuration.ConfigManager.GetXmlConfiguration(System.String)
  id: GetXmlConfiguration(System.String)
  parent: Sdl.Core.PluginFramework.Configuration.ConfigManager
  langs:
  - csharp
  - vb
  name: GetXmlConfiguration(String)
  nameWithType: ConfigManager.GetXmlConfiguration(String)
  fullName: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetXmlConfiguration(System.String)
  type: Method
  source:
    path: Sdl.Core.PluginFramework
    isExternal: true
  assemblies:
  - Sdl.Core.PluginFramework
  namespace: Sdl.Core.PluginFramework.Configuration
  syntax:
    content: public IFrameworkConfiguration GetXmlConfiguration(string pluginConfigFilePath)
    parameters:
    - id: pluginConfigFilePath
      type: System.String
    return:
      type: Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
    content.vb: Public Function GetXmlConfiguration(pluginConfigFilePath As String) As IFrameworkConfiguration
  overload: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetXmlConfiguration*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.PluginFramework.Configuration.ConfigManager.#ctor
  commentId: M:Sdl.Core.PluginFramework.Configuration.ConfigManager.#ctor
  id: '#ctor'
  parent: Sdl.Core.PluginFramework.Configuration.ConfigManager
  langs:
  - csharp
  - vb
  name: ConfigManager()
  nameWithType: ConfigManager.ConfigManager()
  fullName: Sdl.Core.PluginFramework.Configuration.ConfigManager.ConfigManager()
  type: Constructor
  source:
    path: Sdl.Core.PluginFramework
    isExternal: true
  assemblies:
  - Sdl.Core.PluginFramework
  namespace: Sdl.Core.PluginFramework.Configuration
  syntax:
    content: public ConfigManager()
    content.vb: Public Sub New
  overload: Sdl.Core.PluginFramework.Configuration.ConfigManager.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Sdl.Core.PluginFramework.Configuration
  commentId: N:Sdl.Core.PluginFramework.Configuration
  isExternal: true
  name: Sdl.Core.PluginFramework.Configuration
  nameWithType: Sdl.Core.PluginFramework.Configuration
  fullName: Sdl.Core.PluginFramework.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetDefaultXmlConfiguration*
  commentId: Overload:Sdl.Core.PluginFramework.Configuration.ConfigManager.GetDefaultXmlConfiguration
  isExternal: true
  name: GetDefaultXmlConfiguration
  nameWithType: ConfigManager.GetDefaultXmlConfiguration
  fullName: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetDefaultXmlConfiguration
- uid: Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
  commentId: T:Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
  parent: Sdl.Core.PluginFramework.Configuration
  isExternal: true
  name: IFrameworkConfiguration
  nameWithType: IFrameworkConfiguration
  fullName: Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
- uid: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetXmlConfiguration*
  commentId: Overload:Sdl.Core.PluginFramework.Configuration.ConfigManager.GetXmlConfiguration
  isExternal: true
  name: GetXmlConfiguration
  nameWithType: ConfigManager.GetXmlConfiguration
  fullName: Sdl.Core.PluginFramework.Configuration.ConfigManager.GetXmlConfiguration
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.Core.PluginFramework.Configuration.ConfigManager.#ctor*
  commentId: Overload:Sdl.Core.PluginFramework.Configuration.ConfigManager.#ctor
  isExternal: true
  name: ConfigManager
  nameWithType: ConfigManager.ConfigManager
  fullName: Sdl.Core.PluginFramework.Configuration.ConfigManager.ConfigManager
