### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings.Implementation.Json
  commentId: N:Sdl.Core.Settings.Implementation.Json
  id: Sdl.Core.Settings.Implementation.Json
  children:
  - Sdl.Core.Settings.Implementation.Json.JsonSettingImpl`1
  - Sdl.Core.Settings.Implementation.Json.JsonSettingsBundle
  - Sdl.Core.Settings.Implementation.Json.JsonSettingsGroup
  langs:
  - csharp
  - vb
  name: Sdl.Core.Settings.Implementation.Json
  nameWithType: Sdl.Core.Settings.Implementation.Json
  fullName: Sdl.Core.Settings.Implementation.Json
  type: Namespace
  assemblies:
  - Sdl.Core.Settings
references:
- uid: Sdl.Core.Settings.Implementation.Json.JsonSettingImpl`1
  commentId: T:Sdl.Core.Settings.Implementation.Json.JsonSettingImpl`1
  parent: Sdl.Core.Settings.Implementation.Json
  isExternal: true
  name: JsonSettingImpl<T>
  nameWithType: JsonSettingImpl<T>
  fullName: Sdl.Core.Settings.Implementation.Json.JsonSettingImpl<T>
  nameWithType.vb: JsonSettingImpl(Of T)
  fullName.vb: Sdl.Core.Settings.Implementation.Json.JsonSettingImpl(Of T)
  name.vb: JsonSettingImpl(Of T)
  spec.csharp:
  - uid: Sdl.Core.Settings.Implementation.Json.JsonSettingImpl`1
    name: JsonSettingImpl
    nameWithType: JsonSettingImpl
    fullName: Sdl.Core.Settings.Implementation.Json.JsonSettingImpl
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Implementation.Json.JsonSettingImpl`1
    name: JsonSettingImpl
    nameWithType: JsonSettingImpl
    fullName: Sdl.Core.Settings.Implementation.Json.JsonSettingImpl
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.Implementation.Json.JsonSettingsBundle
  commentId: T:Sdl.Core.Settings.Implementation.Json.JsonSettingsBundle
  isExternal: true
  name: JsonSettingsBundle
  nameWithType: JsonSettingsBundle
  fullName: Sdl.Core.Settings.Implementation.Json.JsonSettingsBundle
- uid: Sdl.Core.Settings.Implementation.Json.JsonSettingsGroup
  commentId: T:Sdl.Core.Settings.Implementation.Json.JsonSettingsGroup
  parent: Sdl.Core.Settings.Implementation.Json
  isExternal: true
  name: JsonSettingsGroup
  nameWithType: JsonSettingsGroup
  fullName: Sdl.Core.Settings.Implementation.Json.JsonSettingsGroup
- uid: Sdl.Core.Settings.Implementation.Json
  commentId: N:Sdl.Core.Settings.Implementation.Json
  isExternal: true
  name: Sdl.Core.Settings.Implementation.Json
  nameWithType: Sdl.Core.Settings.Implementation.Json
  fullName: Sdl.Core.Settings.Implementation.Json
