### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings.ISettingsBundleAware
  commentId: T:Sdl.Core.Settings.ISettingsBundleAware
  id: ISettingsBundleAware
  parent: Sdl.Core.Settings
  children:
  - Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  langs:
  - csharp
  - vb
  name: ISettingsBundleAware
  nameWithType: ISettingsBundleAware
  fullName: Sdl.Core.Settings.ISettingsBundleAware
  type: Interface
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public interface ISettingsBundleAware
    content.vb: Public Interface ISettingsBundleAware
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  commentId: M:Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  id: SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  parent: Sdl.Core.Settings.ISettingsBundleAware
  langs:
  - csharp
  - vb
  name: SetSettingsBundle(ISettingsBundle)
  nameWithType: ISettingsBundleAware.SetSettingsBundle(ISettingsBundle)
  fullName: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  type: Method
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: void SetSettingsBundle(ISettingsBundle settingsBundle)
    parameters:
    - id: settingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    content.vb: Sub SetSettingsBundle(settingsBundle As ISettingsBundle)
  overload: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle*
references:
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  isExternal: true
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
- uid: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle*
  commentId: Overload:Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle
  isExternal: true
  name: SetSettingsBundle
  nameWithType: ISettingsBundleAware.SetSettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle
- uid: Sdl.Core.Settings.ISettingsBundle
  commentId: T:Sdl.Core.Settings.ISettingsBundle
  parent: Sdl.Core.Settings
  isExternal: true
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
