### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  id: ImportSettings.TUUpdateMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.AddNew
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.KeepMostRecent
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.LeaveUnchanged
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.Overwrite
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.OverwriteCurrent
  langs:
  - csharp
  - vb
  name: ImportSettings.TUUpdateMode
  nameWithType: ImportSettings.TUUpdateMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  type: Enum
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public enum TUUpdateMode
    content.vb: Public Enum TUUpdateMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.AddNew
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.AddNew
  id: AddNew
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: AddNew
  nameWithType: ImportSettings.TUUpdateMode.AddNew
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.AddNew
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: AddNew = 0
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.Overwrite
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.Overwrite
  id: Overwrite
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: Overwrite
  nameWithType: ImportSettings.TUUpdateMode.Overwrite
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.Overwrite
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: Overwrite = 1
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.LeaveUnchanged
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.LeaveUnchanged
  id: LeaveUnchanged
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: LeaveUnchanged
  nameWithType: ImportSettings.TUUpdateMode.LeaveUnchanged
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.LeaveUnchanged
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: LeaveUnchanged = 2
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.KeepMostRecent
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.KeepMostRecent
  id: KeepMostRecent
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: KeepMostRecent
  nameWithType: ImportSettings.TUUpdateMode.KeepMostRecent
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.KeepMostRecent
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: KeepMostRecent = 3
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.OverwriteCurrent
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.OverwriteCurrent
  id: OverwriteCurrent
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: OverwriteCurrent
  nameWithType: ImportSettings.TUUpdateMode.OverwriteCurrent
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.OverwriteCurrent
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: OverwriteCurrent = 4
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: ImportSettings.TUUpdateMode
  nameWithType: ImportSettings.TUUpdateMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
